/* ============================================================
   FIOMIO, K-beauty active knowledge base
   Each active is decoded and weighted (not merely listed):
   how well it serves each concern, its traits, gentleness,
   timing, and the conflicts that drive the "handle with care"
   guidance. Bilingual FR/EN.
   ============================================================ */

export type ConcernKey =
  | "redness"
  | "dehydration"
  | "dullness"
  | "aging"
  | "acne"
  | "pores"
  | "barrier"
  | "pigmentation"
  | "sunspots"
  | "hormonalredness"
  | "flaking"
  | "darkcircles"
  | "postacne"
  | "oiliness";

export type TraitKey =
  | "hydrating"
  | "barrier"
  | "antioxidant"
  | "soothing"
  | "oilControl"
  | "exfoliating"
  | "brightening"
  | "firming"
  | "occlusive";

export type ActiveUse = "retinoid" | "exfoliant" | "vitc" | "none";
export type Timing = "AM" | "PM" | "AM/PM";

export type Ingredient = {
  id: string;
  name: { fr: string; en: string };
  /** short class / aka shown under the name */
  tag: { fr: string; en: string };
  /** 0–3 efficacy per concern (absent = 0) */
  targets: Partial<Record<ConcernKey, number>>;
  traits: TraitKey[];
  /** 0 = potent/irritating, 3 = very gentle (safe for reactive skin) */
  gentleness: number;
  timing: Timing;
  /** suits these skin types especially (bonus) */
  loves: Array<"dry" | "combination" | "oily" | "normal">;
  why: { fr: string; en: string };
  howToUse: { fr: string; en: string };
  /** raises a caution when the user already uses one of these */
  conflictsWith?: ActiveUse[];
  /** flagged as a "strong" active for sensitivity penalties */
  strong?: boolean;
};

export const INGREDIENTS: Ingredient[] = [
  {
    id: "ceramides",
    name: { fr: "Céramides", en: "Ceramides" },
    tag: { fr: "Réparateur barrière", en: "Barrier repair" },
    targets: { barrier: 3, dehydration: 3, redness: 2, aging: 1 },
    traits: ["barrier", "hydrating", "soothing", "occlusive"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "combination", "normal"],
    why: {
      fr: "Reconstituent le ciment lipidique de la peau, affaibli par l'air sec local et les actifs forts. La base d'une barrière qui retient l'eau.",
      en: "Rebuild the skin's lipid mortar, weakened by dry local air and strong actives. The foundation of a barrier that holds water.",
    },
    howToUse: {
      fr: "Matin et soir, après les sérums, avant la crème (ou dans la crème).",
      en: "Morning and night, after serums, before moisturizer (or within it).",
    },
  },
  {
    id: "hyaluronic",
    name: { fr: "Acide hyaluronique", en: "Hyaluronic acid" },
    tag: { fr: "Hydratant humectant", en: "Humectant hydrator" },
    targets: { dehydration: 3, dullness: 1, aging: 1 },
    traits: ["hydrating"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "combination", "oily", "normal"],
    why: {
      fr: "Capte l'eau dans les couches superficielles pour repulper instantanément. Idéal quand la déshydratation prime sur le manque de lipides.",
      en: "Draws water into the upper layers for instant plumping. Ideal when dehydration outweighs a lack of lipids.",
    },
    howToUse: {
      fr: "Sur peau légèrement humide, puis scellez avec une crème, sinon il peut assécher en air très sec.",
      en: "On slightly damp skin, then seal with a cream, otherwise it can dry you out in very dry air.",
    },
  },
  {
    id: "niacinamide",
    name: { fr: "Niacinamide", en: "Niacinamide" },
    tag: { fr: "Polyvalent · vitamine B3", en: "Multitasker · vitamin B3" },
    targets: {
      pores: 3,
      acne: 2,
      dullness: 2,
      redness: 2,
      barrier: 2,
      pigmentation: 2,
      dehydration: 1,
    },
    traits: ["oilControl", "brightening", "soothing", "barrier"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["combination", "oily", "normal", "dry"],
    why: {
      fr: "Régule le sébum, resserre l'aspect des pores, unifie le teint et soutient la barrière, sans irriter. Compatible avec presque tout, y compris le rétinol en alternance.",
      en: "Regulates sebum, refines the look of pores, evens tone and supports the barrier, without irritation. Plays well with almost everything, including retinol on alternate nights.",
    },
    howToUse: {
      fr: "Matin et/ou soir. 5 % suffisent ; au-delà, risque d'inconfort sur peau réactive.",
      en: "Morning and/or night. 5% is plenty; higher can feel uncomfortable on reactive skin.",
    },
  },
  {
    id: "centella",
    name: { fr: "Centella asiatica (Cica)", en: "Centella asiatica (Cica)" },
    tag: { fr: "Apaisant K-beauty", en: "K-beauty soother" },
    targets: { redness: 3, barrier: 2, dehydration: 1, aging: 1 },
    traits: ["soothing", "barrier", "antioxidant"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "combination", "normal", "oily"],
    why: {
      fr: "Calme les rougeurs réactionnelles spécifiques aux peaux sensibles et accélère la réparation. Le pilier apaisant de la K-beauty.",
      en: "Calms the reactive redness typical of sensitive skin and speeds repair. K-beauty's soothing cornerstone.",
    },
    howToUse: {
      fr: "Matin et soir, en sérum ou essence, particulièrement après un actif fort.",
      en: "Morning and night, as a serum or essence, especially after a strong active.",
    },
  },
  {
    id: "madecassoside",
    name: { fr: "Madécassoside", en: "Madecassoside" },
    tag: { fr: "Cica concentré", en: "Concentrated cica" },
    targets: { redness: 3, barrier: 2, aging: 1 },
    traits: ["soothing", "barrier"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "combination", "normal"],
    why: {
      fr: "Molécule la plus active de la centella : cible la rougeur installée et soutient la cicatrisation de la barrière.",
      en: "The most active molecule in centella: targets entrenched redness and supports barrier recovery.",
    },
    howToUse: {
      fr: "Soir de préférence, en cure pendant les périodes de réactivité.",
      en: "Preferably at night, as a course during reactive periods.",
    },
  },
  {
    id: "panthenol",
    name: { fr: "Panthénol (B5)", en: "Panthenol (B5)" },
    tag: { fr: "Hydratant apaisant", en: "Soothing humectant" },
    targets: { dehydration: 2, barrier: 2, redness: 2 },
    traits: ["hydrating", "soothing", "barrier"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "combination", "normal", "oily"],
    why: {
      fr: "Attire l'eau et apaise l'inflammation : un tampon idéal quand le rétinol ou le froid irritent.",
      en: "Attracts water and calms inflammation: an ideal buffer when retinol or cold irritate.",
    },
    howToUse: {
      fr: "Matin et soir ; superpose bien avec presque tous les actifs.",
      en: "Morning and night; layers well with almost any active.",
    },
  },
  {
    id: "squalane",
    name: { fr: "Squalane", en: "Squalane" },
    tag: { fr: "Émollient léger", en: "Light emollient" },
    targets: { dehydration: 2, barrier: 2 },
    traits: ["occlusive", "barrier", "hydrating"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "normal", "combination"],
    why: {
      fr: "Scelle l'hydratation sans effet gras ni comédon, parfait pour verrouiller un sérum hydratant dans l'air sec hivernal.",
      en: "Seals in hydration with no greasiness or clogging, perfect to lock a hydrating serum into dry winter air.",
    },
    howToUse: {
      fr: "En dernière étape du soir, quelques gouttes sur peau encore humide.",
      en: "As the last evening step, a few drops on still-damp skin.",
    },
  },
  {
    id: "snail",
    name: { fr: "Mucine d'escargot", en: "Snail mucin" },
    tag: { fr: "Réparateur hydratant", en: "Hydrating repair" },
    targets: { dehydration: 2, barrier: 2, dullness: 1, redness: 1, acne: 1 },
    traits: ["hydrating", "barrier", "soothing"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "combination", "normal", "oily"],
    why: {
      fr: "Hydrate, répare et apaise simultanément, un favori K-beauty pour redonner du rebond aux peaux fatiguées.",
      en: "Hydrates, repairs and soothes at once, a K-beauty favorite to bring bounce back to tired skin.",
    },
    howToUse: {
      fr: "En essence après le nettoyage, matin et soir.",
      en: "As an essence after cleansing, morning and night.",
    },
  },
  {
    id: "vitaminc",
    name: { fr: "Vitamine C", en: "Vitamin C" },
    tag: { fr: "Antioxydant · éclat", en: "Antioxidant · glow" },
    targets: { dullness: 3, pigmentation: 3, aging: 2 },
    traits: ["antioxidant", "brightening", "firming"],
    gentleness: 1,
    timing: "AM",
    loves: ["combination", "oily", "normal", "dry"],
    why: {
      fr: "Neutralise les radicaux libres de la pollution urbaine et ravive l'éclat tout en estompant les taches. Le bouclier antioxydant du matin.",
      en: "Neutralizes free radicals from urban pollution and revives glow while fading dark spots. The morning antioxidant shield.",
    },
    howToUse: {
      fr: "Le matin, sous la protection solaire. Introduisez progressivement si votre peau est réactive.",
      en: "In the morning, under sunscreen. Introduce gradually if your skin is reactive.",
    },
    conflictsWith: ["exfoliant"],
    strong: true,
  },
  {
    id: "azelaic",
    name: { fr: "Acide azélaïque", en: "Azelaic acid" },
    tag: { fr: "Anti-rougeurs · taches", en: "Anti-redness · spots" },
    targets: { redness: 3, acne: 2, pigmentation: 2, pores: 1 },
    traits: ["soothing", "brightening", "oilControl"],
    gentleness: 2,
    timing: "AM/PM",
    loves: ["combination", "oily", "normal"],
    why: {
      fr: "Rare polyvalent qui apaise les rougeurs, déloge les imperfections et estompe les taches, bien toléré même par les peaux réactives.",
      en: "A rare multitasker that calms redness, clears breakouts and fades marks, well tolerated even by reactive skin.",
    },
    howToUse: {
      fr: "Matin ou soir ; introduisez un jour sur deux au début.",
      en: "Morning or night; start every other day.",
    },
  },
  {
    id: "salicylic",
    name: { fr: "Acide salicylique (BHA)", en: "Salicylic acid (BHA)" },
    tag: { fr: "Exfoliant des pores", en: "Pore exfoliant" },
    targets: { acne: 3, pores: 3, dullness: 1 },
    traits: ["exfoliating", "oilControl"],
    gentleness: 1,
    timing: "PM",
    loves: ["oily", "combination"],
    why: {
      fr: "Liposoluble, il pénètre dans le pore pour déloger le sébum et désincruster, l'actif clé contre imperfections et points noirs.",
      en: "Oil-soluble, it gets inside the pore to clear sebum and decongest, the key active against breakouts and blackheads.",
    },
    howToUse: {
      fr: "Le soir, 2–3 fois par semaine. Jamais le même soir que le rétinol.",
      en: "At night, 2–3 times a week. Never the same night as retinol.",
    },
    conflictsWith: ["retinoid", "exfoliant"],
    strong: true,
  },
  {
    id: "retinol",
    name: { fr: "Rétinol", en: "Retinol" },
    tag: { fr: "Anti-âge de référence", en: "Gold-standard anti-aging" },
    targets: { aging: 3, pores: 2, pigmentation: 2, acne: 1 },
    traits: ["firming", "exfoliating"],
    gentleness: 0,
    timing: "PM",
    loves: ["normal", "combination", "oily"],
    why: {
      fr: "L'actif anti-âge le plus documenté : stimule le renouvellement et la fermeté. Puissant, à introduire lentement, jamais sans hydratation.",
      en: "The most documented anti-aging active: drives cell turnover and firmness. Potent, introduce slowly, never without hydration.",
    },
    howToUse: {
      fr: "Le soir, 1–2 fois par semaine au début, encadré de céramides. SPF obligatoire le lendemain.",
      en: "At night, 1–2 times a week to start, buffered with ceramides. SPF the next day is non-negotiable.",
    },
    conflictsWith: ["retinoid", "exfoliant", "vitc"],
    strong: true,
  },
  {
    id: "peptides",
    name: { fr: "Peptides", en: "Peptides" },
    tag: { fr: "Fermeté en douceur", en: "Gentle firming" },
    targets: { aging: 3, barrier: 1, dehydration: 1 },
    traits: ["firming", "barrier"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "normal", "combination"],
    why: {
      fr: "Signalent à la peau de produire collagène et élastine, sans l'irritation du rétinol, l'anti-âge des peaux sensibles.",
      en: "Signal the skin to build collagen and elastin, without retinol's irritation, anti-aging for sensitive skin.",
    },
    howToUse: {
      fr: "Matin et soir ; excellent partenaire du rétinol pour amortir son agressivité.",
      en: "Morning and night; an excellent partner to retinol to cushion its harshness.",
    },
  },
  {
    id: "allantoin",
    name: { fr: "Allantoïne", en: "Allantoin" },
    tag: { fr: "Réparateur apaisant", en: "Soothing healer" },
    targets: { redness: 2, barrier: 2, dehydration: 1 },
    traits: ["soothing", "barrier"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "combination", "normal", "oily"],
    why: {
      fr: "Apaise et lisse les peaux irritées, accélère la réparation, un actif discret mais fiable pour calmer une barrière malmenée.",
      en: "Soothes and smooths irritated skin and speeds repair, a quiet but reliable active to calm a stressed barrier.",
    },
    howToUse: {
      fr: "Matin et soir ; se superpose à tout sans risque.",
      en: "Morning and night; layers with anything, risk-free.",
    },
  },
  {
    id: "betaglucan",
    name: { fr: "Bêta-glucane", en: "Beta-glucan" },
    tag: { fr: "Hydratant apaisant", en: "Soothing hydrator" },
    targets: { dehydration: 3, barrier: 2, redness: 2, aging: 1 },
    traits: ["hydrating", "soothing", "barrier"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "combination", "normal", "oily"],
    why: {
      fr: "Retient l'eau plus longtemps que l'acide hyaluronique et calme l'inflammation, un hydratant de fond très bien toléré.",
      en: "Holds water longer than hyaluronic acid and calms inflammation, a very well-tolerated everyday hydrator.",
    },
    howToUse: {
      fr: "Matin et soir, en sérum ou essence, avant les soins plus riches.",
      en: "Morning and night, as a serum or essence, before richer care.",
    },
  },
  {
    id: "mugwort",
    name: { fr: "Armoise (Mugwort)", en: "Mugwort (Artemisia)" },
    tag: { fr: "Apaisant K-beauty", en: "K-beauty soother" },
    targets: { redness: 3, barrier: 2, dehydration: 1 },
    traits: ["soothing", "barrier", "antioxidant"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "combination", "normal", "oily"],
    why: {
      fr: "Star coréenne des peaux irritées : riche en antioxydants, elle calme en profondeur les rougeurs et les démangeaisons.",
      en: "A Korean hero for irritated skin: rich in antioxidants, it deeply calms redness and itch.",
    },
    howToUse: {
      fr: "En essence ou masque, matin et soir, pendant les poussées de réactivité.",
      en: "As an essence or mask, morning and night, during reactive flare-ups.",
    },
  },
  {
    id: "heartleaf",
    name: { fr: "Heartleaf (Houttuynia)", en: "Heartleaf (Houttuynia)" },
    tag: { fr: "Apaisant anti-imperfections", en: "Blemish-calming soother" },
    targets: { redness: 2, acne: 2, barrier: 1, pores: 1 },
    traits: ["soothing", "oilControl", "antioxidant"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["oily", "combination", "normal"],
    why: {
      fr: "Apaise sans assécher : idéal pour les peaux mixtes à imperfections qui réagissent mal aux actifs trop forts.",
      en: "Calms without drying: ideal for blemish-prone combination skin that reacts badly to harsh actives.",
    },
    howToUse: {
      fr: "Matin et soir, après le nettoyage ; cumulable avec un actif anti-imperfections doux.",
      en: "Morning and night, after cleansing; pairs with a gentle blemish active.",
    },
  },
  {
    id: "greentea",
    name: { fr: "Thé vert (EGCG)", en: "Green tea (EGCG)" },
    tag: { fr: "Antioxydant · sébo-régulateur", en: "Antioxidant · sebum control" },
    targets: { redness: 2, acne: 1, dullness: 1, pores: 1 },
    traits: ["antioxidant", "soothing", "oilControl"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["oily", "combination", "normal", "dry"],
    why: {
      fr: "Bouclier antioxydant doux contre la pollution locale, tout en régulant le sébum, parfait en couche du matin.",
      en: "A gentle antioxidant shield against local pollution while regulating sebum, perfect as a morning layer.",
    },
    howToUse: {
      fr: "Le matin sous la protection solaire ; convient aussi le soir.",
      en: "In the morning under sunscreen; also fine at night.",
    },
  },
  {
    id: "galactomyces",
    name: { fr: "Galactomyces (ferment)", en: "Galactomyces (ferment)" },
    tag: { fr: "Essence éclat K-beauty", en: "K-beauty glow essence" },
    targets: { dullness: 2, pores: 2, dehydration: 1, pigmentation: 1 },
    traits: ["brightening", "hydrating", "antioxidant"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["combination", "normal", "oily", "dry"],
    why: {
      fr: "Ferment emblématique des essences coréennes : affine le grain de peau et ravive l'éclat sans agresser.",
      en: "The signature ferment of Korean essences: refines texture and revives glow without aggression.",
    },
    howToUse: {
      fr: "En essence juste après le nettoyage, matin et soir, sur peau humide.",
      en: "As an essence right after cleansing, morning and night, on damp skin.",
    },
  },
  {
    id: "propolis",
    name: { fr: "Propolis", en: "Propolis" },
    tag: { fr: "Apaisant nourrissant", en: "Nourishing soother" },
    targets: { acne: 2, redness: 2, dullness: 1, dehydration: 1 },
    traits: ["soothing", "antioxidant", "barrier"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "combination", "normal", "oily"],
    why: {
      fr: "Apaisant et assainissant à la fois : nourrit les peaux ternes et fatiguées tout en aidant à limiter les imperfections.",
      en: "Soothing and clarifying at once: nourishes dull, tired skin while helping keep blemishes in check.",
    },
    howToUse: {
      fr: "Le soir en sérum ou ampoule, en cure pendant les périodes de fatigue cutanée.",
      en: "At night as a serum or ampoule, as a course during periods of skin fatigue.",
    },
  },
  {
    id: "bakuchiol",
    name: { fr: "Bakuchiol", en: "Bakuchiol" },
    tag: { fr: "Alternative douce au rétinol", en: "Gentle retinol alternative" },
    targets: { aging: 3, pigmentation: 1, redness: 1, barrier: 1 },
    traits: ["firming", "antioxidant", "soothing"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "normal", "combination", "oily"],
    why: {
      fr: "Effet lissant proche du rétinol sans l'irritation ni la photosensibilité, l'anti-âge des peaux sensibles ou déjà sous actifs.",
      en: "A retinol-like smoothing effect without the irritation or photosensitivity, anti-aging for sensitive skin or those already on actives.",
    },
    howToUse: {
      fr: "Matin et/ou soir ; se cumule sans risque, même avec une barrière fragilisée.",
      en: "Morning and/or night; stacks safely, even on a compromised barrier.",
    },
  },
  {
    id: "tranexamic",
    name: { fr: "Acide tranexamique", en: "Tranexamic acid" },
    tag: { fr: "Anti-taches ciblé", en: "Targeted spot-fader" },
    targets: { pigmentation: 3, redness: 2, dullness: 1 },
    traits: ["brightening", "soothing"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["combination", "normal", "dry", "oily"],
    why: {
      fr: "Cible les taches tenaces et les marques post-inflammatoires sans irriter, efficace là où la vitamine C est mal tolérée.",
      en: "Targets stubborn spots and post-inflammatory marks without irritation, effective where vitamin C isn't tolerated.",
    },
    howToUse: {
      fr: "Matin et soir ; se superpose bien à la niacinamide pour un effet anti-taches renforcé.",
      en: "Morning and night; layers well with niacinamide for a stronger spot-fading effect.",
    },
  },
  {
    id: "arbutin",
    name: { fr: "Alpha-arbutine", en: "Alpha-arbutin" },
    tag: { fr: "Éclaircissant doux", en: "Gentle brightener" },
    targets: { pigmentation: 3, dullness: 2 },
    traits: ["brightening"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["combination", "normal", "dry", "oily"],
    why: {
      fr: "Freine en douceur la production de mélanine pour estomper taches et hyperpigmentation, sans effet rebond.",
      en: "Gently slows melanin production to fade spots and hyperpigmentation, with no rebound effect.",
    },
    howToUse: {
      fr: "Matin et soir, en cure de plusieurs semaines ; SPF indispensable le jour.",
      en: "Morning and night, over several weeks; daytime SPF is essential.",
    },
  },
  {
    id: "mandelic",
    name: { fr: "Acide mandélique (AHA)", en: "Mandelic acid (AHA)" },
    tag: { fr: "Exfoliant doux peaux sensibles", en: "Gentle AHA for sensitive skin" },
    targets: { acne: 2, pigmentation: 2, dullness: 2, pores: 1 },
    traits: ["exfoliating", "brightening", "oilControl"],
    gentleness: 2,
    timing: "PM",
    loves: ["oily", "combination", "normal"],
    why: {
      fr: "AHA à grosse molécule, donc le plus doux : exfolie, lisse et unifie sans la réactivité du glycolique.",
      en: "A large-molecule AHA, hence the gentlest: exfoliates, smooths and evens without glycolic's reactivity.",
    },
    howToUse: {
      fr: "Le soir, 2–3 fois par semaine ; jamais le même soir que le rétinol.",
      en: "At night, 2–3 times a week; never the same night as retinol.",
    },
    conflictsWith: ["retinoid", "exfoliant"],
    strong: true,
  },
  {
    id: "glycolic",
    name: { fr: "Acide glycolique (AHA)", en: "Glycolic acid (AHA)" },
    tag: { fr: "Exfoliant éclat", en: "Glow exfoliant" },
    targets: { dullness: 3, pigmentation: 2, aging: 2, pores: 2 },
    traits: ["exfoliating", "brightening"],
    gentleness: 1,
    timing: "PM",
    loves: ["normal", "combination", "oily"],
    why: {
      fr: "Le plus pénétrant des AHA : ravive l'éclat et lisse la texture, mais demande une barrière solide et une introduction progressive.",
      en: "The most penetrating AHA: revives glow and smooths texture, but needs a solid barrier and gradual introduction.",
    },
    howToUse: {
      fr: "Le soir, 1–2 fois par semaine au début. SPF obligatoire le lendemain.",
      en: "At night, 1–2 times a week to start. SPF the next day is mandatory.",
    },
    conflictsWith: ["retinoid", "exfoliant", "vitc"],
    strong: true,
  },
  {
    id: "lactic",
    name: { fr: "Acide lactique (AHA)", en: "Lactic acid (AHA)" },
    tag: { fr: "Exfoliant hydratant", en: "Hydrating exfoliant" },
    targets: { dullness: 2, dehydration: 2, pigmentation: 2, pores: 1 },
    traits: ["exfoliating", "hydrating", "brightening"],
    gentleness: 2,
    timing: "PM",
    loves: ["dry", "normal", "combination"],
    why: {
      fr: "AHA qui exfolie tout en hydratant : idéal pour les peaux sèches et ternes qui ne supportent pas le glycolique.",
      en: "An AHA that exfoliates while hydrating: ideal for dry, dull skin that can't tolerate glycolic.",
    },
    howToUse: {
      fr: "Le soir, 2 fois par semaine ; suivi d'une crème réparatrice.",
      en: "At night, twice a week; follow with a repairing cream.",
    },
    conflictsWith: ["retinoid", "exfoliant"],
    strong: true,
  },
  {
    id: "pha",
    name: { fr: "PHA (gluconolactone)", en: "PHA (gluconolactone)" },
    tag: { fr: "Exfoliant le plus doux", en: "The gentlest exfoliant" },
    targets: { pores: 2, dullness: 2, barrier: 1 },
    traits: ["exfoliating", "hydrating"],
    gentleness: 2,
    timing: "PM",
    loves: ["dry", "combination", "normal", "oily"],
    why: {
      fr: "Acide à très grosse molécule qui exfolie en surface et retient l'eau, l'entrée idéale vers les acides pour peaux réactives.",
      en: "A very large-molecule acid that exfoliates the surface and holds water, the ideal gateway into acids for reactive skin.",
    },
    howToUse: {
      fr: "Le soir, 2–3 fois par semaine ; bien mieux toléré que les AHA classiques.",
      en: "At night, 2–3 times a week; far better tolerated than classic AHAs.",
    },
    conflictsWith: ["retinoid", "exfoliant"],
  },
  {
    id: "adenosine",
    name: { fr: "Adénosine", en: "Adenosine" },
    tag: { fr: "Anti-âge cellulaire", en: "Cellular anti-aging" },
    targets: { aging: 3, dullness: 1 },
    traits: ["firming", "soothing"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "normal", "combination", "oily"],
    why: {
      fr: "Actif anti-rides reconnu : stimule la production de collagène et lisse les ridules, tout en restant très bien toléré.",
      en: "A well-recognised anti-wrinkle active: stimulates collagen and smooths fine lines while staying very well tolerated.",
    },
    howToUse: {
      fr: "Matin et soir, dans un sérum ou une crème. Se superpose sans conflit aux autres actifs.",
      en: "Morning and night, in a serum or cream. Layers with other actives without conflict.",
    },
  },
  {
    id: "tocopherol",
    name: { fr: "Vitamine E (tocophérol)", en: "Vitamin E (tocopherol)" },
    tag: { fr: "Antioxydant lipidique", en: "Lipid antioxidant" },
    targets: { aging: 1, barrier: 2, dehydration: 1 },
    traits: ["antioxidant", "barrier", "occlusive"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "normal", "combination"],
    why: {
      fr: "Antioxydant liposoluble qui protège les lipides de la barrière et renforce la vitamine C. Le duo C + E défend mieux contre les UV et la pollution.",
      en: "A fat-soluble antioxidant that protects barrier lipids and boosts vitamin C. The C + E duo defends better against UV and pollution.",
    },
    howToUse: {
      fr: "Matin sous la protection solaire, idéalement avec de la vitamine C.",
      en: "Morning under sunscreen, ideally alongside vitamin C.",
    },
  },
  {
    id: "ferulic",
    name: { fr: "Acide férulique", en: "Ferulic acid" },
    tag: { fr: "Stabilisateur antioxydant", en: "Antioxidant stabiliser" },
    targets: { aging: 2, dullness: 1 },
    traits: ["antioxidant", "brightening"],
    gentleness: 2,
    timing: "AM",
    loves: ["normal", "combination", "oily", "dry"],
    why: {
      fr: "Antioxydant qui stabilise et démultiplie l'action de la vitamine C et E le matin, pour une défense renforcée contre le stress oxydatif.",
      en: "An antioxidant that stabilises and amplifies vitamins C and E in the morning, for stronger defense against oxidative stress.",
    },
    howToUse: {
      fr: "Le matin, dans un sérum antioxydant, avant la protection solaire.",
      en: "In the morning, in an antioxidant serum, before sunscreen.",
    },
  },
  {
    id: "licorice",
    name: { fr: "Réglisse (glabridine)", en: "Licorice (glabridin)" },
    tag: { fr: "Éclaircissant apaisant", en: "Soothing brightener" },
    targets: { pigmentation: 2, redness: 2, dullness: 2 },
    traits: ["brightening", "soothing", "antioxidant"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["combination", "oily", "normal", "dry"],
    why: {
      fr: "Freine la production de mélanine et apaise les rougeurs en même temps : idéal pour les taches sur peau sensible, sans agresser.",
      en: "Slows melanin production and calms redness at once: ideal for dark spots on sensitive skin, without aggression.",
    },
    howToUse: {
      fr: "Matin et soir. Se marie bien avec la niacinamide et la vitamine C.",
      en: "Morning and night. Pairs well with niacinamide and vitamin C.",
    },
  },
  {
    id: "zincpca",
    name: { fr: "Zinc PCA", en: "Zinc PCA" },
    tag: { fr: "Séborégulateur", en: "Sebum balancer" },
    targets: { acne: 2, pores: 2, redness: 1 },
    traits: ["oilControl", "soothing"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["oily", "combination"],
    why: {
      fr: "Régule la production de sébum et calme l'inflammation des imperfections, sans décaper la peau comme le font les nettoyants agressifs.",
      en: "Regulates sebum and calms breakout inflammation, without stripping the skin the way harsh cleansers do.",
    },
    howToUse: {
      fr: "Matin et/ou soir, dans un sérum léger. Souvent associé à la niacinamide.",
      en: "Morning and/or night, in a light serum. Often paired with niacinamide.",
    },
  },
  {
    id: "polyglutamic",
    name: { fr: "Acide polyglutamique", en: "Polyglutamic acid" },
    tag: { fr: "Hydratant haute capacité", en: "High-capacity humectant" },
    targets: { dehydration: 3, dullness: 1 },
    traits: ["hydrating"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "normal", "combination", "oily"],
    why: {
      fr: "Humectant qui retient plusieurs fois plus d'eau que l'acide hyaluronique en surface et forme un film hydratant lissant.",
      en: "A humectant that holds several times more surface water than hyaluronic acid and forms a smoothing hydration film.",
    },
    howToUse: {
      fr: "Sur peau humide, avant les crèmes. Excellent par-dessus l'acide hyaluronique.",
      en: "On damp skin, before creams. Excellent layered over hyaluronic acid.",
    },
  },
  {
    id: "ginseng",
    name: { fr: "Ginseng (Panax)", en: "Ginseng (Panax)" },
    tag: { fr: "Antioxydant tonifiant", en: "Energising antioxidant" },
    targets: { aging: 2, dullness: 2 },
    traits: ["antioxidant", "firming", "brightening"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["normal", "dry", "combination"],
    why: {
      fr: "Ingrédient phare de la K-beauty : riche en saponines antioxydantes, il ravive l'éclat et soutient la fermeté d'un teint fatigué.",
      en: "A K-beauty hero: rich in antioxidant saponins, it revives radiance and supports firmness in tired-looking skin.",
    },
    howToUse: {
      fr: "Matin ou soir, en essence ou sérum. Parfait dans une routine éclat.",
      en: "Morning or night, as an essence or serum. Perfect in a radiance routine.",
    },
  },
  {
    id: "rice",
    name: { fr: "Extrait de riz (Oryza sativa)", en: "Rice extract (Oryza sativa)" },
    tag: { fr: "Éclat et confort", en: "Glow and comfort" },
    targets: { dullness: 2, dehydration: 1, redness: 1 },
    traits: ["brightening", "soothing", "hydrating"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "normal", "combination", "oily"],
    why: {
      fr: "Riche en antioxydants et en sucres hydratants, il unifie et illumine le teint en douceur, une base traditionnelle des soins coréens.",
      en: "Rich in antioxidants and hydrating sugars, it gently evens and brightens the complexion, a traditional staple of Korean skincare.",
    },
    howToUse: {
      fr: "Matin et soir, en essence. Très bien toléré, même sur peau sensible.",
      en: "Morning and night, as an essence. Very well tolerated, even on sensitive skin.",
    },
  },
  {
    id: "ectoin",
    name: { fr: "Ectoïne", en: "Ectoin" },
    tag: { fr: "Bouclier hydratant", en: "Hydration shield" },
    targets: { dehydration: 2, barrier: 2, redness: 2 },
    traits: ["hydrating", "barrier", "soothing"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "normal", "combination"],
    why: {
      fr: "Molécule de protection issue de micro-organismes extrêmes : retient l'eau et protège les cellules du stress (froid, pollution, chauffage).",
      en: "A protective molecule from extremophile microbes: holds water and shields cells from stress (cold, pollution, indoor heating).",
    },
    howToUse: {
      fr: "Matin et soir. Particulièrement utile en hiver et en environnement urbain.",
      en: "Morning and night. Especially useful in winter and urban environments.",
    },
  },
  {
    id: "urea",
    name: { fr: "Urée", en: "Urea" },
    tag: { fr: "Hydratant kératolytique", en: "Humectant keratolytic" },
    targets: { dehydration: 3, barrier: 2 },
    traits: ["hydrating", "barrier"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "normal"],
    why: {
      fr: "Composant naturel du facteur d'hydratation de la peau : retient l'eau et, à faible dose, lisse les zones rugueuses sans irriter.",
      en: "A natural component of the skin's moisturising factor: holds water and, at low levels, smooths rough patches without irritation.",
    },
    howToUse: {
      fr: "Le soir dans une crème. À 5–10 % pour hydrater ; au-delà, effet plus exfoliant.",
      en: "At night in a cream. 5–10% to hydrate; higher becomes more exfoliating.",
    },
  },
  {
    id: "resveratrol",
    name: { fr: "Resvératrol", en: "Resveratrol" },
    tag: { fr: "Antioxydant de nuit", en: "Nighttime antioxidant" },
    targets: { aging: 2, dullness: 1 },
    traits: ["antioxidant", "firming"],
    gentleness: 2,
    timing: "PM",
    loves: ["normal", "dry", "combination"],
    why: {
      fr: "Antioxydant végétal puissant qui agit la nuit pour neutraliser les radicaux libres et soutenir la réparation cellulaire.",
      en: "A potent plant antioxidant that works overnight to neutralise free radicals and support cellular repair.",
    },
    howToUse: {
      fr: "Le soir, avant la crème. Complémentaire des antioxydants du matin.",
      en: "At night, before moisturizer. Complements morning antioxidants.",
    },
  },
  {
    id: "q10",
    name: { fr: "Coenzyme Q10", en: "Coenzyme Q10" },
    tag: { fr: "Antioxydant énergisant", en: "Energising antioxidant" },
    targets: { aging: 2, dullness: 1 },
    traits: ["antioxidant", "firming"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["normal", "dry", "combination"],
    why: {
      fr: "Antioxydant naturellement présent dans la peau, qui décline avec l'âge : il soutient l'énergie cellulaire et la fermeté.",
      en: "An antioxidant naturally present in skin that declines with age: it supports cellular energy and firmness.",
    },
    howToUse: {
      fr: "Matin et/ou soir, dans un sérum ou une crème.",
      en: "Morning and/or night, in a serum or cream.",
    },
  },
  {
    id: "lactobionic",
    name: { fr: "Acide lactobionique (PHA)", en: "Lactobionic acid (PHA)" },
    tag: { fr: "Exfoliant antioxydant doux", en: "Gentle antioxidant exfoliant" },
    targets: { dullness: 2, dehydration: 1, pores: 1 },
    traits: ["exfoliating", "hydrating", "antioxidant"],
    gentleness: 2,
    timing: "PM",
    loves: ["dry", "normal", "combination", "oily"],
    why: {
      fr: "PHA à grosse molécule : exfolie en surface, retient l'eau et apporte un effet antioxydant, mieux toléré que les AHA classiques.",
      en: "A large-molecule PHA: surface-exfoliates, holds water and adds antioxidant action, better tolerated than classic AHAs.",
    },
    howToUse: {
      fr: "Le soir, 2–3 fois par semaine. À ne pas cumuler avec un autre acide le même soir.",
      en: "At night, 2–3 times a week. Don't stack with another acid on the same night.",
    },
    conflictsWith: ["retinoid", "exfoliant"],
  },
  {
    id: "kojic",
    name: { fr: "Acide kojique", en: "Kojic acid" },
    tag: { fr: "Anti-taches ciblé", en: "Targeted spot-fader" },
    targets: { pigmentation: 3, dullness: 1 },
    traits: ["brightening"],
    gentleness: 2,
    timing: "AM/PM",
    loves: ["normal", "combination", "oily"],
    strong: true,
    why: {
      fr: "Inhibe la tyrosinase, l'enzyme clé de la pigmentation : efficace sur les taches tenaces, mais peut sensibiliser les peaux réactives.",
      en: "Inhibits tyrosinase, the key pigmentation enzyme: effective on stubborn dark spots, but can sensitise reactive skin.",
    },
    howToUse: {
      fr: "Introduire progressivement, avec une protection solaire stricte le jour.",
      en: "Introduce gradually, with strict daytime sun protection.",
    },
  },
  {
    id: "caffeine",
    name: { fr: "Caféine", en: "Caffeine" },
    tag: { fr: "Antioxydant décongestionnant", en: "De-puffing antioxidant" },
    targets: { dullness: 1, aging: 1 },
    traits: ["antioxidant"],
    gentleness: 3,
    timing: "AM",
    loves: ["normal", "combination", "oily", "dry"],
    why: {
      fr: "Antioxydant qui stimule la microcirculation : utile le matin pour décongestionner et raviver le regard et le teint fatigués.",
      en: "An antioxidant that stimulates microcirculation: useful in the morning to de-puff and revive tired-looking eyes and skin.",
    },
    howToUse: {
      fr: "Le matin, sur le contour de l'œil ou le visage, avant les soins hydratants.",
      en: "In the morning, on the eye area or face, before hydrating care.",
    },
  },
  {
    id: "sheabutter",
    name: { fr: "Beurre de karité", en: "Shea butter" },
    tag: { fr: "Occlusif nourrissant", en: "Nourishing occlusive" },
    targets: { barrier: 2, dehydration: 2 },
    traits: ["occlusive", "barrier", "hydrating"],
    gentleness: 3,
    timing: "PM",
    loves: ["dry", "normal"],
    why: {
      fr: "Riche en acides gras et en vitamines, il scelle l'hydratation et restaure le confort des peaux sèches ou malmenées par le froid.",
      en: "Rich in fatty acids and vitamins, it seals in hydration and restores comfort to dry or cold-stressed skin.",
    },
    howToUse: {
      fr: "Le soir, en dernière étape, pour verrouiller les soins. À doser sur peau mixte à grasse.",
      en: "At night, as the last step, to lock in care. Use sparingly on combination-to-oily skin.",
    },
  },
  {
    id: "pdrn",
    name: { fr: "PDRN (ADN de saumon)", en: "PDRN (salmon DNA)" },
    tag: { fr: "Régénérant réparateur", en: "Regenerating repair" },
    targets: { aging: 2, barrier: 2, redness: 2, dehydration: 1 },
    traits: ["firming", "soothing", "barrier"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "normal", "combination", "oily"],
    why: {
      fr: "Polynucléotides qui stimulent la réparation cellulaire et l'élasticité, tout en apaisant. L'actif star des routines régénérantes coréennes.",
      en: "Polynucleotides that stimulate cellular repair and elasticity while soothing. The hero active of Korean regenerating routines.",
    },
    howToUse: {
      fr: "Matin et soir, en sérum, avant la crème. Très bien toléré, même sur peau fragilisée.",
      en: "Morning and night, as a serum, before moisturizer. Very well tolerated, even on compromised skin.",
    },
  },
  {
    id: "collagen",
    name: { fr: "Collagène hydrolysé", en: "Hydrolyzed collagen" },
    tag: { fr: "Repulpant hydratant", en: "Plumping hydrator" },
    targets: { dehydration: 2, aging: 1 },
    traits: ["hydrating", "firming"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "normal", "combination"],
    why: {
      fr: "De petits peptides de collagène qui retiennent l'eau en surface et lissent l'aspect de la peau pour un fini repulpé.",
      en: "Small collagen peptides that hold water at the surface and smooth the skin's look for a plumped finish.",
    },
    howToUse: {
      fr: "Matin et soir, en essence ou sérum, sur peau humide.",
      en: "Morning and night, as an essence or serum, on damp skin.",
    },
  },
  {
    id: "teatree",
    name: { fr: "Arbre à thé (Tea tree)", en: "Tea tree" },
    tag: { fr: "Anti-imperfections", en: "Blemish fighter" },
    targets: { acne: 3, pores: 2, redness: 1 },
    traits: ["oilControl", "soothing"],
    gentleness: 2,
    timing: "AM/PM",
    loves: ["oily", "combination"],
    strong: true,
    why: {
      fr: "Huile essentielle purifiante qui cible les boutons et l'excès de sébum. Efficace mais à doser sur peau réactive.",
      en: "A purifying essential oil that targets blemishes and excess sebum. Effective, but use sparingly on reactive skin.",
    },
    howToUse: {
      fr: "En soin localisé ou dilué dans un sérum. Évitez les fortes concentrations au quotidien.",
      en: "As a spot treatment or diluted in a serum. Avoid high concentrations daily.",
    },
  },
  {
    id: "aloe",
    name: { fr: "Aloe vera", en: "Aloe vera" },
    tag: { fr: "Apaisant rafraîchissant", en: "Cooling soother" },
    targets: { redness: 2, dehydration: 2, barrier: 1 },
    traits: ["soothing", "hydrating"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "normal", "combination", "oily"],
    why: {
      fr: "Hydrate et calme la peau échauffée (soleil, vent, réactivité), avec une texture légère qui convient à tous les types de peau.",
      en: "Hydrates and calms heated skin (sun, wind, reactivity), with a light texture that suits all skin types.",
    },
    howToUse: {
      fr: "Matin et soir, en gel ou essence, après le nettoyage.",
      en: "Morning and night, as a gel or essence, after cleansing.",
    },
  },
  {
    id: "bifida",
    name: { fr: "Ferment de bifida", en: "Bifida ferment" },
    tag: { fr: "Microbiome et barrière", en: "Microbiome and barrier" },
    targets: { barrier: 2, redness: 1, aging: 1, dehydration: 1 },
    traits: ["soothing", "barrier", "antioxidant"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "normal", "combination", "oily"],
    why: {
      fr: "Lysat de ferment qui soutient le microbiome cutané, renforce la barrière et améliore la résistance de la peau au stress.",
      en: "A ferment lysate that supports the skin microbiome, strengthens the barrier and improves resilience to stress.",
    },
    howToUse: {
      fr: "Matin et soir, en essence ou sérum. Se marie avec presque tout.",
      en: "Morning and night, as an essence or serum. Pairs with almost everything.",
    },
  },
  {
    id: "cholesterol",
    name: { fr: "Cholestérol", en: "Cholesterol" },
    tag: { fr: "Lipide de barrière", en: "Barrier lipid" },
    targets: { barrier: 2, dehydration: 1 },
    traits: ["barrier", "occlusive"],
    gentleness: 3,
    timing: "PM",
    loves: ["dry", "normal"],
    why: {
      fr: "L'un des trois lipides essentiels de la barrière, avec les céramides et les acides gras. Reconstruit le ciment cutané et limite la perte d'eau.",
      en: "One of the three essential barrier lipids, alongside ceramides and fatty acids. Rebuilds the skin's mortar and limits water loss.",
    },
    howToUse: {
      fr: "Le soir, dans une crème réparatrice, idéalement avec des céramides.",
      en: "At night, in a repair cream, ideally alongside ceramides.",
    },
  },
  {
    id: "glutathione",
    name: { fr: "Glutathion", en: "Glutathione" },
    tag: { fr: "Antioxydant éclaircissant", en: "Brightening antioxidant" },
    targets: { pigmentation: 2, dullness: 2 },
    traits: ["antioxidant", "brightening"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["normal", "combination", "oily", "dry"],
    why: {
      fr: "Antioxydant majeur de la peau qui neutralise les radicaux libres et freine la production de mélanine pour un teint plus clair et uniforme.",
      en: "A master skin antioxidant that neutralises free radicals and slows melanin production for a brighter, more even tone.",
    },
    howToUse: {
      fr: "Matin et/ou soir, en sérum. Synergique avec la vitamine C.",
      en: "Morning and/or night, as a serum. Synergistic with vitamin C.",
    },
  },
  {
    id: "mulberry",
    name: { fr: "Extrait de mûrier", en: "Mulberry extract" },
    tag: { fr: "Anti-taches végétal", en: "Botanical spot-fader" },
    targets: { pigmentation: 2, dullness: 1 },
    traits: ["brightening"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["normal", "combination", "dry"],
    why: {
      fr: "Inhibiteur naturel de la tyrosinase qui cible les taches et illumine le teint, en douceur.",
      en: "A natural tyrosinase inhibitor that targets dark spots and brightens the complexion, gently.",
    },
    howToUse: {
      fr: "Matin et soir, en sérum, avec une protection solaire le jour.",
      en: "Morning and night, as a serum, with daytime sun protection.",
    },
  },
  {
    id: "oat",
    name: { fr: "Avoine colloïdale", en: "Colloidal oat" },
    tag: { fr: "Apaisant anti-démangeaisons", en: "Anti-itch soother" },
    targets: { redness: 2, barrier: 2, dehydration: 1 },
    traits: ["soothing", "barrier", "hydrating"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "normal", "combination"],
    why: {
      fr: "Reconnue pour calmer les irritations et les démangeaisons, elle apaise les peaux sensibles et soutient la barrière.",
      en: "Recognised for calming irritation and itching, it soothes sensitive skin and supports the barrier.",
    },
    howToUse: {
      fr: "Matin et soir, en crème ou lait, sur peau réactive ou sèche.",
      en: "Morning and night, in a cream or lotion, on reactive or dry skin.",
    },
  },
  {
    id: "witchhazel",
    name: { fr: "Hamamélis", en: "Witch hazel" },
    tag: { fr: "Astringent doux", en: "Gentle astringent" },
    targets: { pores: 2, acne: 1, redness: 1 },
    traits: ["oilControl", "soothing"],
    gentleness: 2,
    timing: "AM/PM",
    loves: ["oily", "combination"],
    why: {
      fr: "Tonifie et resserre l'aspect des pores tout en apaisant. Préférez les formules sans alcool pour éviter de dessécher.",
      en: "Tones and refines the look of pores while soothing. Prefer alcohol-free formulas to avoid drying.",
    },
    howToUse: {
      fr: "En toner, matin et soir. À limiter si la peau tiraille.",
      en: "As a toner, morning and night. Cut back if skin feels tight.",
    },
  },
  {
    id: "jojoba",
    name: { fr: "Huile de jojoba", en: "Jojoba oil" },
    tag: { fr: "Huile équilibrante", en: "Balancing oil" },
    targets: { barrier: 1, dehydration: 1 },
    traits: ["occlusive", "hydrating"],
    gentleness: 3,
    timing: "PM",
    loves: ["dry", "combination"],
    why: {
      fr: "Proche du sébum humain, elle nourrit sans étouffer et aide à rééquilibrer les peaux mixtes comme sèches.",
      en: "Close to human sebum, it nourishes without suffocating and helps rebalance both combination and dry skin.",
    },
    howToUse: {
      fr: "Le soir, en dernière étape ou mélangée à la crème. Quelques gouttes suffisent.",
      en: "At night, as a last step or mixed into moisturizer. A few drops are enough.",
    },
  },
  {
    id: "rosehip",
    name: { fr: "Huile de rose musquée", en: "Rosehip oil" },
    tag: { fr: "Huile éclat antioxydante", en: "Antioxidant glow oil" },
    targets: { dullness: 1, aging: 1, pigmentation: 1, barrier: 1 },
    traits: ["antioxidant", "barrier", "brightening"],
    gentleness: 3,
    timing: "PM",
    loves: ["dry", "normal"],
    why: {
      fr: "Riche en caroténoïdes et acides gras, elle ravive l'éclat, nourrit la barrière et aide à atténuer les marques.",
      en: "Rich in carotenoids and fatty acids, it revives radiance, nourishes the barrier and helps fade marks.",
    },
    howToUse: {
      fr: "Le soir, quelques gouttes après les sérums. Sensible à l'oxydation : conservez à l'abri de la lumière.",
      en: "At night, a few drops after serums. Prone to oxidation: store away from light.",
    },
  },
  {
    id: "calendula",
    name: { fr: "Calendula (souci)", en: "Calendula" },
    tag: { fr: "Apaisant réparateur", en: "Soothing repair" },
    targets: { redness: 2, barrier: 1 },
    traits: ["soothing", "barrier"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "normal", "combination"],
    why: {
      fr: "Plante apaisante traditionnelle qui calme les rougeurs et les irritations et soutient la réparation de la peau sensible.",
      en: "A traditional soothing botanical that calms redness and irritation and supports repair in sensitive skin.",
    },
    howToUse: {
      fr: "Matin et soir, en essence, huile ou crème apaisante.",
      en: "Morning and night, in a soothing essence, oil or cream.",
    },
  },
  {
    id: "snowmushroom",
    name: { fr: "Champignon des neiges (Tremella)", en: "Snow mushroom (Tremella)" },
    tag: { fr: "Humectant nouvelle génération", en: "Next-gen humectant" },
    targets: { dehydration: 3, dullness: 1 },
    traits: ["hydrating"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "normal", "combination", "oily"],
    why: {
      fr: "Retient l'eau encore mieux que l'acide hyaluronique, avec des particules plus fines qui pénètrent pour une hydratation rebondie.",
      en: "Holds water even better than hyaluronic acid, with finer particles that sink in for bouncy hydration.",
    },
    howToUse: {
      fr: "Matin et soir, en essence ou sérum, sur peau humide.",
      en: "Morning and night, as an essence or serum, on damp skin.",
    },
  },
  {
    id: "betaine",
    name: { fr: "Bétaïne", en: "Betaine" },
    tag: { fr: "Humectant apaisant", en: "Soothing humectant" },
    targets: { dehydration: 2, redness: 1 },
    traits: ["hydrating", "soothing"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "normal", "combination", "oily"],
    why: {
      fr: "Humectant doux issu de la betterave qui hydrate et adoucit sans alourdir, tout en réduisant la sensation d'inconfort.",
      en: "A gentle beet-derived humectant that hydrates and softens without heaviness, while easing discomfort.",
    },
    howToUse: {
      fr: "Matin et soir. Souvent associé à l'acide hyaluronique dans les formules hydratantes.",
      en: "Morning and night. Often paired with hyaluronic acid in hydrating formulas.",
    },
  },
  {
    id: "linoleic",
    name: { fr: "Acide linoléique (vitamine F)", en: "Linoleic acid (vitamin F)" },
    tag: { fr: "Lipide barrière non comédogène", en: "Non-comedogenic barrier lipid" },
    targets: { barrier: 2, acne: 1, redness: 1 },
    traits: ["barrier", "soothing"],
    gentleness: 3,
    timing: "PM",
    loves: ["oily", "combination", "dry"],
    why: { fr: "Acide gras essentiel qui renforce la barrière sans obstruer les pores, utile pour les peaux grasses sujettes aux imperfections.", en: "An essential fatty acid that reinforces the barrier without clogging pores, useful for oily, blemish-prone skin." },
    howToUse: { fr: "Le soir, en huile légère ou sérum, sur peau propre.", en: "At night, as a light oil or serum, on clean skin." },
  },
  {
    id: "honey",
    name: { fr: "Miel", en: "Honey" },
    tag: { fr: "Humectant apaisant", en: "Soothing humectant" },
    targets: { dehydration: 2, redness: 1, barrier: 1 },
    traits: ["hydrating", "soothing"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "normal", "combination"],
    why: { fr: "Attire et retient l'eau tout en apaisant : un humectant doux aux propriétés réconfortantes.", en: "Draws and holds water while calming: a gentle humectant with comforting properties." },
    howToUse: { fr: "Matin et soir, en masque ou soin hydratant.", en: "Morning and night, in a mask or hydrating treatment." },
  },
  {
    id: "clay",
    name: { fr: "Argile (kaolin)", en: "Clay (kaolin)" },
    tag: { fr: "Absorbeur de sébum", en: "Sebum absorber" },
    targets: { pores: 2, acne: 1 },
    traits: ["oilControl"],
    gentleness: 2,
    timing: "PM",
    loves: ["oily", "combination"],
    why: { fr: "Absorbe l'excès de sébum et désincruste les pores ; idéale en masque hebdomadaire pour les peaux grasses.", en: "Absorbs excess sebum and clears pores; ideal as a weekly mask for oily skin." },
    howToUse: { fr: "En masque, 1 à 2 fois par semaine. À ne pas laisser sécher complètement.", en: "As a mask, 1–2 times a week. Don't let it fully dry out." },
  },
  {
    id: "charcoal",
    name: { fr: "Charbon actif", en: "Activated charcoal" },
    tag: { fr: "Détox des pores", en: "Pore detox" },
    targets: { pores: 2, acne: 1 },
    traits: ["oilControl"],
    gentleness: 2,
    timing: "PM",
    loves: ["oily", "combination"],
    why: { fr: "Capte les impuretés et l'excès de sébum, pour des pores plus nets sur les peaux mixtes à grasses.", en: "Captures impurities and excess sebum, for clearer pores on combination-to-oily skin." },
    howToUse: { fr: "En masque ou nettoyant, 1 à 2 fois par semaine.", en: "As a mask or cleanser, 1–2 times a week." },
  },
  {
    id: "sulfur",
    name: { fr: "Soufre", en: "Sulfur" },
    tag: { fr: "Anti-acné asséchant", en: "Drying anti-acne" },
    targets: { acne: 3, pores: 1 },
    traits: ["oilControl"],
    gentleness: 2,
    timing: "PM",
    loves: ["oily", "combination"],
    strong: true,
    why: { fr: "Actif anti-imperfections qui assèche les boutons et régule le sébum ; efficace mais potentiellement desséchant.", en: "A blemish-fighting active that dries up spots and regulates sebum; effective but potentially drying." },
    howToUse: { fr: "En soin localisé le soir. Hydratez bien autour.", en: "As a spot treatment at night. Moisturize well around it." },
  },
  {
    id: "algae",
    name: { fr: "Algues (laminaire)", en: "Algae (kelp)" },
    tag: { fr: "Minéraux marins hydratants", en: "Hydrating marine minerals" },
    targets: { dehydration: 2, redness: 1, dullness: 1 },
    traits: ["hydrating", "antioxidant", "soothing"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "normal", "combination", "oily"],
    why: { fr: "Riche en minéraux et antioxydants marins, hydrate et protège la peau du stress environnemental.", en: "Rich in marine minerals and antioxidants, hydrates and protects skin from environmental stress." },
    howToUse: { fr: "Matin et soir, en essence ou crème.", en: "Morning and night, in an essence or cream." },
  },
  {
    id: "retinal",
    name: { fr: "Rétinaldéhyde (rétinal)", en: "Retinaldehyde (retinal)" },
    tag: { fr: "Rétinoïde plus rapide", en: "Faster retinoid" },
    targets: { aging: 3, acne: 2, pores: 1 },
    traits: ["firming"],
    gentleness: 2,
    timing: "PM",
    loves: ["normal", "combination", "oily"],
    strong: true,
    why: { fr: "Plus puissant que le rétinol et plus rapide à agir, tout en restant mieux toléré que la trétinoïne. Renouvelle et lisse.", en: "More potent than retinol and faster acting, while better tolerated than tretinoin. Renews and smooths." },
    howToUse: { fr: "Le soir, progressivement. SPF strict le jour, à éviter pendant la grossesse.", en: "At night, build up gradually. Strict daytime SPF, avoid during pregnancy." },
  },
  {
    id: "argan",
    name: { fr: "Huile d'argan", en: "Argan oil" },
    tag: { fr: "Huile nourrissante", en: "Nourishing oil" },
    targets: { barrier: 1, dehydration: 1, aging: 1 },
    traits: ["occlusive", "barrier", "antioxidant"],
    gentleness: 3,
    timing: "PM",
    loves: ["dry", "normal"],
    why: { fr: "Riche en vitamine E et acides gras, nourrit et assouplit la peau sèche tout en limitant la perte d'eau.", en: "Rich in vitamin E and fatty acids, nourishes and softens dry skin while limiting water loss." },
    howToUse: { fr: "Le soir, quelques gouttes en dernière étape.", en: "At night, a few drops as a final step." },
  },
  {
    id: "exosome",
    name: { fr: "Exosomes", en: "Exosomes" },
    tag: { fr: "Régénérant nouvelle génération", en: "Next-gen regenerative" },
    targets: { aging: 2, barrier: 2, redness: 1 },
    traits: ["firming", "barrier", "soothing"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["normal", "dry", "combination"],
    why: { fr: "Vecteurs de signaux cellulaires qui soutiennent la réparation et l'élasticité ; l'une des pistes les plus récentes du soin coréen.", en: "Carriers of cellular signals that support repair and elasticity; one of the newest frontiers in Korean skincare." },
    howToUse: { fr: "Matin et soir, en sérum, sur peau propre.", en: "Morning and night, as a serum, on clean skin." },
  },
  {
    id: "seabuckthorn",
    name: { fr: "Argousier", en: "Sea buckthorn" },
    tag: { fr: "Huile antioxydante orange", en: "Orange antioxidant oil" },
    targets: { dullness: 1, aging: 1, barrier: 1 },
    traits: ["antioxidant", "barrier"],
    gentleness: 3,
    timing: "PM",
    loves: ["dry", "normal"],
    why: { fr: "Exceptionnellement riche en caroténoïdes et oméga, ravive l'éclat et soutient la réparation de la barrière.", en: "Exceptionally rich in carotenoids and omegas, revives radiance and supports barrier repair." },
    howToUse: { fr: "Le soir, quelques gouttes ; sa couleur orangée s'estompe à l'application.", en: "At night, a few drops; its orange tint fades on application." },
  },
  {
    id: "ginkgo",
    name: { fr: "Ginkgo biloba", en: "Ginkgo biloba" },
    tag: { fr: "Antioxydant circulatoire", en: "Circulation antioxidant" },
    targets: { dullness: 1, redness: 1, aging: 1 },
    traits: ["antioxidant", "soothing"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["normal", "dry", "combination"],
    why: { fr: "Antioxydant végétal qui apaise et soutient la microcirculation pour un teint plus reposé.", en: "A plant antioxidant that soothes and supports microcirculation for a more rested complexion." },
    howToUse: { fr: "Matin et soir, en essence ou sérum.", en: "Morning and night, in an essence or serum." },
  },
  {
    id: "enzyme",
    name: { fr: "Enzymes de fruits", en: "Fruit enzymes" },
    tag: { fr: "Exfoliant enzymatique doux", en: "Gentle enzyme exfoliant" },
    targets: { dullness: 2, pores: 1 },
    traits: ["exfoliating"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["dry", "normal", "combination", "oily"],
    why: { fr: "Dissolvent en douceur les cellules mortes pour révéler l'éclat, sans la friction d'un gommage ni l'agressivité des acides forts.", en: "Gently dissolve dead cells to reveal radiance, without the friction of a scrub or the harshness of strong acids." },
    howToUse: { fr: "En poudre ou masque, 1 à 3 fois par semaine.", en: "As a powder or mask, 1–3 times a week." },
  },
  {
    id: "edelweiss",
    name: { fr: "Edelweiss", en: "Edelweiss" },
    tag: { fr: "Antioxydant alpin", en: "Alpine antioxidant" },
    targets: { aging: 1, redness: 1, dullness: 1 },
    traits: ["antioxidant", "soothing"],
    gentleness: 3,
    timing: "AM/PM",
    loves: ["normal", "dry", "combination"],
    why: { fr: "Plante de haute montagne très antioxydante, qui protège la peau du stress et apaise les rougeurs.", en: "A highly antioxidant alpine plant that protects skin from stress and calms redness." },
    howToUse: { fr: "Matin et soir, en sérum ou crème.", en: "Morning and night, in a serum or cream." },
  },
  {
    id: "willowbark",
    name: { fr: "Écorce de saule", en: "Willow bark" },
    tag: { fr: "BHA naturel doux", en: "Gentle natural BHA" },
    targets: { acne: 2, pores: 2, dullness: 1 },
    traits: ["exfoliating", "oilControl", "soothing"],
    gentleness: 2,
    timing: "AM/PM",
    loves: ["oily", "combination", "normal"],
    why: { fr: "Source naturelle de salicylates qui exfolie en douceur et désincruste les pores, mieux tolérée que le BHA pur.", en: "A natural source of salicylates that gently exfoliates and clears pores, better tolerated than pure BHA." },
    howToUse: { fr: "En toner ou sérum, en introduisant progressivement.", en: "As a toner or serum, introducing gradually." },
  },
];

export function getIngredient(id: string): Ingredient | undefined {
  return INGREDIENTS.find((i) => i.id === id);
}


// Concerns ajoutées (taches solaires, rougeurs hormonales, sécheresse desquamante)
// mappées ici pour garder les entrées principales lisibles. Fusionné au chargement.
const EXTRA_TARGETS: Record<string, Partial<Record<ConcernKey, number>>> = {
  vitaminc: { sunspots: 3, postacne: 2, darkcircles: 1 },
  tranexamic: { sunspots: 3, postacne: 2 },
  arbutin: { sunspots: 3, postacne: 1, darkcircles: 1 },
  niacinamide: { sunspots: 2, hormonalredness: 1, postacne: 3, oiliness: 3, darkcircles: 2 },
  azelaic: { sunspots: 2, hormonalredness: 3, postacne: 3 },
  kojic: { sunspots: 2 },
  licorice: { sunspots: 2, hormonalredness: 2, postacne: 1 },
  glutathione: { sunspots: 2 },
  mulberry: { sunspots: 2 },
  ferulic: { sunspots: 1 },
  resveratrol: { sunspots: 1 },
  tocopherol: { sunspots: 1, darkcircles: 1 },
  centella: { hormonalredness: 2, postacne: 2 },
  madecassoside: { hormonalredness: 2, postacne: 1 },
  allantoin: { hormonalredness: 2, flaking: 1, postacne: 1 },
  greentea: { hormonalredness: 1, oiliness: 2 },
  heartleaf: { hormonalredness: 1, oiliness: 1 },
  mugwort: { hormonalredness: 1, oiliness: 1 },
  calendula: { hormonalredness: 1 },
  betaglucan: { hormonalredness: 1, flaking: 1 },
  panthenol: { hormonalredness: 1, flaking: 2 },
  urea: { flaking: 3 },
  lactic: { flaking: 2 },
  pha: { flaking: 2 },
  lactobionic: { flaking: 2 },
  mandelic: { flaking: 1 },
  ceramides: { flaking: 2 },
  squalane: { flaking: 2 },
  sheabutter: { flaking: 2 },
  oat: { flaking: 2 },
  jojoba: { flaking: 1 },
  caffeine: { darkcircles: 3 },
  peptides: { darkcircles: 2 },
  adenosine: { darkcircles: 2 },
  retinol: { darkcircles: 1 },
  ginkgo: { darkcircles: 1 },
  zincpca: { oiliness: 3 },
  witchhazel: { oiliness: 2 },
  salicylic: { oiliness: 2 },
  clay: { oiliness: 2 },
  charcoal: { oiliness: 1 },
  willowbark: { oiliness: 1 },
};

for (const ing of INGREDIENTS) {
  const extra = EXTRA_TARGETS[ing.id];
  if (extra) Object.assign(ing.targets, extra);
}
