// DRAFT catalog — product NAMES are real & well-known. Links are generated as
// YesStyle search URLs (a configured affiliate partner), so every link resolves
// and is auto-affiliated. No prices (confirm at launch). Swap to exact product
// pages later if desired.

import type { ConcernKey } from "@/lib/ingredients";

export const PRODUCTS_DRAFT = true;

/** Build a YesStyle search URL for a product (a configured affiliate partner).
 *  YesStyle's canonical search path is /en/list.html?q=… (verified). Spaces → "+". */
/** Concise, high-match query: brand + the first 2 meaningful words of the name
 *  (drops form words/numbers that make YesStyle search return nothing). */
function shortQuery(brand: string, name: string): string {
  const toks = name
    .replace(/[^A-Za-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter((t) => /[A-Za-z]/.test(t))
    .slice(0, 2);
  return [brand, ...toks].filter(Boolean).join(" ").trim();
}

export function yesstyleSearchUrl(query: string): string {
  const q = encodeURIComponent(query).replace(/%20/g, "+");
  return `https://www.yesstyle.com/en/list.html?q=${q}`;
}

export function productSearchUrl(p: Product): string {
  return p.url ?? yesstyleSearchUrl(shortQuery(p.brand, p.name));
}

export function searchUrlForName(brand: string | undefined, name: string): string {
  return yesstyleSearchUrl(shortQuery(brand ?? "", name));
}

export type Product = {
  id: string;
  brand: string;
  name: string;
  /** short, brand-led YesStyle query (full names are too exact to match) */
  searchQ: string;
  /** exact YesStyle product page (verified); when absent, searchQ is used */
  url?: string;
  ingredientIds: string[];
  concerns?: ConcernKey[];
  category:
    | "cleanser"
    | "toner"
    | "essence"
    | "serum"
    | "moisturizer"
    | "sunscreen"
    | "treatment"
    | "mask";
  blurb: { fr: string; en: string };
};

/* Real, well-known K-beauty products mapped to our active ids.
   Links are built at render time via yesstyleSearchUrl(searchQ) →
   buildAffiliateLink(), so they always resolve and carry our affiliate tag. */
export const PRODUCTS: Product[] = [
  {
    id: "cosrx-snail-96",
    url: "https://www.yesstyle.com/en/cosrx-advanced-snail-96-mucin-power-essence-100ml/info.html/pid.1052684695",
    brand: "COSRX",
    name: "Advanced Snail 96 Mucin Power Essence",
    searchQ: "COSRX Snail 96 Essence",
    ingredientIds: ["snail"],
    concerns: ["dehydration", "barrier"],
    category: "essence",
    blurb: {
      fr: "Essence mucine : répare et repulpe la barrière en douceur.",
      en: "Snail-mucin essence: gently repairs and plumps the barrier.",
    },
  },
  {
    id: "anua-heartleaf-77",
    url: "https://www.yesstyle.com/en/anua-heartleaf-77-soothing-toner-250ml/info.html/pid.1134551762",
    brand: "Anua",
    name: "Heartleaf 77% Soothing Toner",
    searchQ: "Anua Heartleaf 77 Toner",
    ingredientIds: ["heartleaf", "centella"],
    concerns: ["redness", "acne"],
    category: "toner",
    blurb: {
      fr: "Toner heartleaf : apaise rougeurs et imperfections sans assécher.",
      en: "Heartleaf toner: calms redness and blemishes without drying.",
    },
  },
  {
    id: "skin1004-centella-ampoule",
    url: "https://www.yesstyle.com/en/skin-1004-madagascar-centella-ampoule-55ml/info.html/pid.1121970671",
    brand: "SKIN1004",
    name: "Madagascar Centella Ampoule",
    searchQ: "SKIN1004 Centella Ampoule",
    ingredientIds: ["centella"],
    concerns: ["redness", "barrier"],
    category: "serum",
    blurb: {
      fr: "Ampoule cica pure : calme la réactivité et soutient la barrière.",
      en: "Pure cica ampoule: calms reactivity and supports the barrier.",
    },
  },
  {
    id: "purito-centella-serum",
    url: "https://www.yesstyle.com/en/purito-centella-unscented-serum-60ml-pcr-bottle/info.html/pid.1104612292",
    brand: "PURITO",
    name: "Centella Unscented Serum",
    searchQ: "PURITO Centella Unscented Serum",
    ingredientIds: ["centella", "panthenol"],
    concerns: ["redness", "barrier"],
    category: "serum",
    blurb: {
      fr: "Sérum cica sans parfum : apaisant minimaliste pour peaux réactives.",
      en: "Fragrance-free cica serum: minimalist soothing for reactive skin.",
    },
  },
  {
    id: "boj-glow-deep-serum",
    url: "https://www.yesstyle.com/en/beauty-of-joseon-glow-deep-serum-30ml/info.html/pid.1103112976",
    brand: "Beauty of Joseon",
    name: "Glow Deep Serum: Rice + Alpha Arbutin",
    searchQ: "Beauty of Joseon Glow Deep Serum",
    ingredientIds: ["niacinamide", "arbutin"],
    concerns: ["dullness", "pigmentation"],
    category: "serum",
    blurb: {
      fr: "Sérum riz et arbutine : ravive l'éclat et estompe les taches.",
      en: "Rice + arbutin serum: revives glow and fades dark spots.",
    },
  },
  {
    id: "boj-revive-serum",
    url: "https://www.yesstyle.com/en/beauty-of-joseon-revive-serum/info.html/pid.1106273718",
    brand: "Beauty of Joseon",
    name: "Revive Serum: Ginseng + Snail Mucin",
    searchQ: "Beauty of Joseon Revive Serum",
    ingredientIds: ["snail", "propolis"],
    concerns: ["dehydration", "barrier"],
    category: "serum",
    blurb: {
      fr: "Sérum ginseng et mucine : nourrit et redonne du rebond.",
      en: "Ginseng + snail serum: nourishes and restores bounce.",
    },
  },
  {
    id: "boj-relief-sun",
    url: "https://www.yesstyle.com/en/beauty-of-joseon-relief-sun-rice-probiotics-50ml/info.html/pid.1107744417",
    brand: "Beauty of Joseon",
    name: "Relief Sun: Rice + Probiotics SPF50+",
    searchQ: "Beauty of Joseon Relief Sun",
    ingredientIds: ["greentea"],
    concerns: ["barrier"],
    category: "sunscreen",
    blurb: {
      fr: "SPF50+ fluide au fini naturel : protection quotidienne agréable.",
      en: "Lightweight SPF50+ with a natural finish: easy daily protection.",
    },
  },
  {
    id: "boj-glow-serum",
    url: "https://www.yesstyle.com/en/beauty-of-joseon-glow-serum-30ml/info.html/pid.1089210994",
    brand: "Beauty of Joseon",
    name: "Glow Serum: Propolis + Niacinamide",
    searchQ: "Beauty of Joseon Propolis Niacinamide Serum",
    ingredientIds: ["propolis", "niacinamide"],
    concerns: ["dullness", "acne"],
    category: "serum",
    blurb: {
      fr: "Propolis et niacinamide : éclat et clarté pour peaux fatiguées.",
      en: "Propolis + niacinamide: glow and clarity for tired skin.",
    },
  },
  {
    id: "numbuzin-no3",
    url: "https://www.yesstyle.com/en/numbuzin-no-3-skin-softening-serum-50ml/info.html/pid.1136288384",
    brand: "Numbuzin",
    name: "No.3 Skin Softening Serum",
    searchQ: "Numbuzin No.3 Serum",
    ingredientIds: ["niacinamide", "galactomyces"],
    concerns: ["dullness", "pigmentation"],
    category: "serum",
    blurb: {
      fr: "Sérum éclat multi-ferments : unifie et illumine le teint.",
      en: "Multi-ferment brightening serum: evens and lights up the complexion.",
    },
  },
  {
    id: "isntree-ha-toner",
    url: "https://www.yesstyle.com/en/isntree-hyaluronic-acid-toner-200ml/info.html/pid.1113252153",
    brand: "Isntree",
    name: "Hyaluronic Acid Toner",
    searchQ: "Isntree Hyaluronic Acid Toner",
    ingredientIds: ["hyaluronic"],
    concerns: ["dehydration"],
    category: "toner",
    blurb: {
      fr: "Toner à l'acide hyaluronique : hydratation repulpante en couches.",
      en: "Hyaluronic acid toner: plumping, layerable hydration.",
    },
  },
  {
    id: "torriden-dive-in-serum",
    url: "https://www.yesstyle.com/en/torriden-dive-in-low-molecule-hyaluronic-acid-serum-renewed-50ml/info.html/pid.1115692618",
    brand: "Torriden",
    name: "DIVE-IN Low Molecular Hyaluronic Acid Serum",
    searchQ: "Torriden Dive-In Serum",
    ingredientIds: ["hyaluronic", "betaglucan"],
    concerns: ["dehydration", "barrier"],
    category: "serum",
    blurb: {
      fr: "Sérum hyaluronique léger : hydrate en profondeur, fini frais.",
      en: "Light hyaluronic serum: deep hydration, fresh finish.",
    },
  },
  {
    id: "aestura-atobarrier365",
    url: "https://www.yesstyle.com/en/aestura-ato-barrier-365-cream-80ml/info.html/pid.1128134342",
    brand: "Aestura",
    name: "Atobarrier365 Cream",
    searchQ: "Aestura Atobarrier365 Cream",
    ingredientIds: ["ceramides", "panthenol"],
    concerns: ["barrier", "dehydration"],
    category: "moisturizer",
    blurb: {
      fr: "Crème céramides : restaure la barrière des peaux sèches et sensibles.",
      en: "Ceramide cream: rebuilds the barrier of dry, sensitive skin.",
    },
  },
  {
    id: "drjart-ceramidin-cream",
    url: "https://www.yesstyle.com/en/dr-jart-ceramidin-skin-barrier-moisturizing-cream-50ml/info.html/pid.1123469827",
    brand: "Dr.Jart+",
    name: "Ceramidin Cream",
    searchQ: "Dr.Jart Ceramidin Cream",
    ingredientIds: ["ceramides"],
    concerns: ["barrier", "dehydration"],
    category: "moisturizer",
    blurb: {
      fr: "Crème ceramidin : confort et étanchéité pour barrière fragilisée.",
      en: "Ceramidin cream: comfort and seal for a compromised barrier.",
    },
  },
  {
    id: "somebymi-retinol",
    brand: "SOME BY MI",
    name: "Retinol Intense Reactivating Serum",
    searchQ: "Some By Mi Retinol Intense Serum",
    url: "https://www.yesstyle.com/en/some-by-mi-retinol-intense-reactivating-serum-2023-version-30ml/info.html/pid.1126717155",
    ingredientIds: ["retinol"],
    concerns: ["aging"],
    category: "serum",
    blurb: {
      fr: "Sérum rétinol progressif : lissage et fermeté, à introduire lentement.",
      en: "Gradual retinol serum: smoothing and firmness, introduce slowly.",
    },
  },
  {
    id: "goodal-vitc",
    brand: "Goodal",
    name: "Green Tangerine Vita C Dark Spot Serum",
    searchQ: "Goodal Green Tangerine Vita C",
    url: "https://www.yesstyle.com/en/goodal-green-tangerine-vita-c-dark-spot-care-serum-40ml/info.html/pid.1112714085",
    ingredientIds: ["vitaminc"],
    concerns: ["dullness", "pigmentation"],
    category: "serum",
    blurb: {
      fr: "Vitamine C de tangerine verte : éclat et atténuation des taches.",
      en: "Green-tangerine vitamin C: glow and dark-spot fading.",
    },
  },
  {
    id: "cosrx-aha-bha-toner",
    url: "https://www.yesstyle.com/en/cosrx-aha-bha-clarifying-treatment-toner-150ml/info.html/pid.1052684721",
    brand: "COSRX",
    name: "AHA/BHA Clarifying Treatment Toner",
    searchQ: "COSRX AHA BHA Clarifying Toner",
    ingredientIds: ["glycolic", "salicylic"],
    concerns: ["pores", "acne"],
    category: "toner",
    blurb: {
      fr: "Toner AHA/BHA : affine le grain et désincruste les pores.",
      en: "AHA/BHA toner: refines texture and decongests pores.",
    },
  },
  {
    id: "cosrx-bha-blackhead",
    url: "https://www.yesstyle.com/en/cosrx-bha-blackhead-power-liquid/info.html/pid.1052684693",
    brand: "COSRX",
    name: "BHA Blackhead Power Liquid",
    searchQ: "COSRX BHA Blackhead Power Liquid",
    ingredientIds: ["salicylic"],
    concerns: ["pores", "acne"],
    category: "treatment",
    blurb: {
      fr: "BHA ciblé : déloge sébum et points noirs au cœur du pore.",
      en: "Targeted BHA: clears sebum and blackheads inside the pore.",
    },
  },
  {
    id: "isntree-mugwort",
    url: "https://www.yesstyle.com/en/isntree-spot-saver-mugwort-ampoule-50ml/info.html/pid.1075256548",
    brand: "Isntree",
    name: "Spot Saver Mugwort Ampoule",
    searchQ: "Isntree Mugwort Ampoule",
    ingredientIds: ["mugwort"],
    concerns: ["redness", "acne"],
    category: "serum",
    blurb: {
      fr: "Ampoule armoise : apaise profondément les peaux irritées.",
      en: "Mugwort ampoule: deeply calms irritated, reactive skin.",
    },
  },
  {
    id: "roundlab-dokdo-toner",
    url: "https://www.yesstyle.com/en/round-lab-1025-dokdo-toner-200ml/info.html/pid.1074112897",
    brand: "Round Lab",
    name: "1025 Dokdo Toner",
    searchQ: "Round Lab Dokdo Toner",
    ingredientIds: ["panthenol", "betaglucan"],
    concerns: ["dehydration", "barrier"],
    category: "toner",
    blurb: {
      fr: "Toner minéral apaisant : hydrate et rééquilibre en douceur.",
      en: "Soothing mineral toner: hydrates and rebalances gently.",
    },
  },
  {
    id: "roundlab-mugwort-cream",
    url: "https://www.yesstyle.com/en/round-lab-mugwort-calming-cream-80ml/info.html/pid.1086574611",
    brand: "Round Lab",
    name: "Mugwort Calming Cream",
    searchQ: "Round Lab Mugwort Cream",
    ingredientIds: ["mugwort", "centella"],
    concerns: ["redness", "barrier"],
    category: "moisturizer",
    blurb: {
      fr: "Crème armoise : calme et nourrit les barrières sensibilisées.",
      en: "Mugwort cream: calms and nourishes sensitised barriers.",
    },
  },
  {
    id: "mixsoon-bean-essence",
    url: "https://www.yesstyle.com/en/mixsoon-bean-essence-50ml/info.html/pid.1105987458",
    brand: "Mixsoon",
    name: "Bean Essence",
    searchQ: "Mixsoon Bean Essence",
    ingredientIds: ["galactomyces", "niacinamide"],
    concerns: ["dullness", "dehydration"],
    category: "essence",
    blurb: {
      fr: "Essence fermentée minimaliste : lisse le grain et ravive l'éclat.",
      en: "Minimalist fermented essence: smooths texture and revives glow.",
    },
  },
  {
    id: "abib-heartleaf-toner",
    url: "https://www.yesstyle.com/en/abib-heartleaf-calming-toner-skin-booster-200ml/info.html/pid.1095458670",
    brand: "Abib",
    name: "Heartleaf Essence Calming Toner",
    searchQ: "Abib Heartleaf Toner",
    ingredientIds: ["heartleaf", "allantoin"],
    concerns: ["redness", "barrier"],
    category: "toner",
    blurb: {
      fr: "Toner heartleaf apaisant : confort immédiat pour peaux sensibles.",
      en: "Soothing heartleaf toner: instant comfort for sensitive skin.",
    },
  },
  {
    id: "axisy-dark-spot-serum",
    url: "https://www.yesstyle.com/en/axis-y-dark-spot-correcting-glow-serum-50ml/info.html/pid.1078919512",
    brand: "AXIS-Y",
    name: "Dark Spot Correcting Glow Serum",
    searchQ: "AXIS-Y Dark Spot Correcting Serum",
    ingredientIds: ["niacinamide", "squalane"],
    concerns: ["pigmentation", "dullness"],
    category: "serum",
    blurb: {
      fr: "Sérum anti-taches : unifie le teint et nourrit légèrement.",
      en: "Dark-spot serum: evens tone with a light nourishing finish.",
    },
  },
  {
    id: "klairs-vitc-drop",
    url: "https://www.yesstyle.com/en/dear-klairs-freshly-juiced-vitamin-drop-35ml/info.html/pid.1060708173",
    brand: "Dear, Klairs",
    name: "Freshly Juiced Vitamin Drop",
    searchQ: "Klairs Freshly Juiced Vitamin Drop",
    ingredientIds: ["vitaminc"],
    concerns: ["dullness", "pigmentation"],
    category: "serum",
    blurb: {
      fr: "Vitamine C douce 5 % : éclat progressif, bien tolérée.",
      en: "Gentle 5% vitamin C: gradual glow, well tolerated.",
    },
  },
  {
    id: "boj-glow-serum",
    brand: "Beauty of Joseon",
    name: "Glow Deep Serum: Rice + Alpha Arbutin",
    searchQ: "Beauty of Joseon Glow Deep Serum",
    ingredientIds: ["rice", "arbutin"],
    concerns: ["dullness", "pigmentation"],
    category: "serum",
    blurb: {
      fr: "Riz et alpha-arbutine : éclat et taches, en douceur.",
      en: "Rice and alpha-arbutin: glow and dark spots, gently.",
    },
  },
  {
    id: "boj-relief-sun",
    brand: "Beauty of Joseon",
    name: "Relief Sun: Rice + Probiotics SPF50+",
    searchQ: "Beauty of Joseon Relief Sun",
    ingredientIds: ["rice"],
    concerns: ["dullness", "barrier"],
    category: "sunscreen",
    blurb: {
      fr: "Filtre solaire au fini naturel, confortable au quotidien.",
      en: "Comfortable daily sunscreen with a natural finish.",
    },
  },
  {
    id: "boj-revive-eye",
    brand: "Beauty of Joseon",
    name: "Revive Eye Serum: Ginseng + Retinal",
    searchQ: "Beauty of Joseon Revive Eye Serum",
    ingredientIds: ["ginseng", "retinol"],
    concerns: ["aging", "dullness"],
    category: "treatment",
    blurb: {
      fr: "Ginseng et rétinal : fermeté et regard reposé.",
      en: "Ginseng and retinal: firmness and a rested look.",
    },
  },
  {
    id: "skin1004-centella-ampoule",
    brand: "SKIN1004",
    name: "Madagascar Centella Ampoule",
    searchQ: "SKIN1004 Madagascar Centella Ampoule",
    ingredientIds: ["centella"],
    concerns: ["redness", "barrier"],
    category: "serum",
    blurb: {
      fr: "Centella pure : apaise les rougeurs et la réactivité.",
      en: "Pure centella: calms redness and reactivity.",
    },
  },
  {
    id: "skin1004-tone-brightening",
    brand: "SKIN1004",
    name: "Centella Tone Brightening Ampoule",
    searchQ: "SKIN1004 Centella Tone Brightening Ampoule",
    ingredientIds: ["vitaminc", "centella"],
    concerns: ["dullness", "pigmentation"],
    category: "serum",
    blurb: {
      fr: "Vitamine C et centella : éclat sans agresser.",
      en: "Vitamin C and centella: glow without aggression.",
    },
  },
  {
    id: "somebymi-miracle-toner",
    brand: "Some By Mi",
    name: "AHA BHA PHA 30 Days Miracle Toner",
    searchQ: "Some By Mi 30 Days Miracle Toner",
    ingredientIds: ["salicylic", "lactic", "pha"],
    concerns: ["acne", "pores"],
    category: "toner",
    blurb: {
      fr: "Trio d'acides doux : grain de peau et imperfections.",
      en: "Gentle acid trio: texture and breakouts.",
    },
  },
  {
    id: "isntree-ha-toner",
    brand: "Isntree",
    name: "Hyaluronic Acid Toner Plus",
    searchQ: "Isntree Hyaluronic Acid Toner",
    ingredientIds: ["hyaluronic"],
    concerns: ["dehydration"],
    category: "toner",
    blurb: {
      fr: "Hydratation longue durée, texture légère.",
      en: "Long-lasting hydration, lightweight texture.",
    },
  },
  {
    id: "isntree-greentea-toner",
    brand: "Isntree",
    name: "Green Tea Fresh Toner",
    searchQ: "Isntree Green Tea Fresh Toner",
    ingredientIds: ["greentea"],
    concerns: ["acne", "pores"],
    category: "toner",
    blurb: {
      fr: "Thé vert antioxydant : équilibre les peaux mixtes à grasses.",
      en: "Antioxidant green tea: balances combination-to-oily skin.",
    },
  },
  {
    id: "torriden-divein-serum",
    brand: "Torriden",
    name: "DIVE-IN Low Molecular Hyaluronic Acid Serum",
    searchQ: "Torriden DIVE-IN Serum",
    ingredientIds: ["hyaluronic", "polyglutamic"],
    concerns: ["dehydration"],
    category: "serum",
    blurb: {
      fr: "Acide hyaluronique multi-poids : repulpe et apaise.",
      en: "Multi-weight hyaluronic acid: plumps and soothes.",
    },
  },
  {
    id: "numbuzin-no3-serum",
    brand: "Numbuzin",
    name: "No.3 Skin Brightening Serum",
    searchQ: "numbuzin No.3 Brightening Serum",
    ingredientIds: ["niacinamide", "vitaminc"],
    concerns: ["dullness", "pigmentation"],
    category: "serum",
    blurb: {
      fr: "Niacinamide et vitamine C : teint plus lumineux et uni.",
      en: "Niacinamide and vitamin C: a brighter, more even tone.",
    },
  },
  {
    id: "anua-niacinamide-txa",
    brand: "Anua",
    name: "Niacinamide 10% + TXA 4% Serum",
    searchQ: "Anua Niacinamide TXA Serum",
    ingredientIds: ["niacinamide", "tranexamic"],
    concerns: ["pigmentation", "dullness"],
    category: "serum",
    blurb: {
      fr: "Duo anti-taches concentré pour les marques tenaces.",
      en: "Concentrated dark-spot duo for stubborn marks.",
    },
  },
  {
    id: "cosrx-snail-92-cream",
    brand: "COSRX",
    name: "Advanced Snail 92 All-in-One Cream",
    searchQ: "COSRX Snail 92 Cream",
    ingredientIds: ["snail"],
    concerns: ["barrier", "dehydration"],
    category: "moisturizer",
    blurb: {
      fr: "Mucine d'escargot : répare et repulpe la barrière.",
      en: "Snail mucin: repairs and plumps the barrier.",
    },
  },
  {
    id: "cosrx-bha-liquid",
    brand: "COSRX",
    name: "BHA Blackhead Power Liquid",
    searchQ: "COSRX BHA Blackhead Power Liquid",
    ingredientIds: ["salicylic"],
    concerns: ["pores", "acne"],
    category: "treatment",
    blurb: {
      fr: "BHA qui désincruste les pores et les points noirs.",
      en: "BHA that clears pores and blackheads.",
    },
  },
  {
    id: "cosrx-retinol-cream",
    brand: "COSRX",
    name: "The Retinol 0.1 Cream",
    searchQ: "COSRX Retinol 0.1 Cream",
    ingredientIds: ["retinol"],
    concerns: ["aging"],
    category: "treatment",
    blurb: {
      fr: "Rétinol débutant pour lisser ridules et texture.",
      en: "Beginner retinol to smooth fine lines and texture.",
    },
  },
  {
    id: "haruharu-blackrice-toner",
    brand: "Haruharu Wonder",
    name: "Black Rice Hyaluronic Toner",
    searchQ: "Haruharu Wonder Black Rice Toner",
    ingredientIds: ["rice", "hyaluronic"],
    concerns: ["dehydration", "dullness"],
    category: "toner",
    blurb: {
      fr: "Riz noir fermenté et hydratation : éclat et confort.",
      en: "Fermented black rice and hydration: glow and comfort.",
    },
  },
  {
    id: "drjart-cicapair-serum",
    brand: "Dr.Jart+",
    name: "Cicapair Tiger Grass Serum",
    searchQ: "Dr.Jart Cicapair Serum",
    ingredientIds: ["centella", "madecassoside"],
    concerns: ["redness", "barrier"],
    category: "serum",
    blurb: {
      fr: "Centella concentrée pour les peaux réactives et fragilisées.",
      en: "Concentrated centella for reactive, compromised skin.",
    },
  },
  {
    id: "roundlab-birch-sun",
    brand: "Round Lab",
    name: "Birch Juice Moisturizing Sunscreen",
    searchQ: "Round Lab Birch Juice Sunscreen",
    ingredientIds: ["hyaluronic"],
    concerns: ["dehydration", "barrier"],
    category: "sunscreen",
    blurb: {
      fr: "Protection hydratante, sans fini blanc ni inconfort.",
      en: "Hydrating protection, no white cast or discomfort.",
    },
  },
  {
    id: "goodal-vitac-serum",
    brand: "Goodal",
    name: "Green Tangerine Vita C Dark Spot Serum",
    searchQ: "Goodal Green Tangerine Vita C Serum",
    ingredientIds: ["vitaminc"],
    concerns: ["pigmentation", "dullness"],
    category: "serum",
    blurb: {
      fr: "Vitamine C de mandarine verte ciblant les taches.",
      en: "Green-tangerine vitamin C targeting dark spots.",
    },
  },
  {
    id: "cosrx-lowph-cleanser",
    brand: "COSRX",
    name: "Low pH Good Morning Gel Cleanser",
    searchQ: "COSRX Low pH Gel Cleanser",
    ingredientIds: ["salicylic"],
    concerns: ["acne", "pores"],
    category: "cleanser",
    blurb: { fr: "Nettoyant doux à pH bas, respecte la barrière.", en: "Low-pH gel cleanser that respects the barrier." },
  },
  {
    id: "cosrx-vitc23-serum",
    brand: "COSRX",
    name: "Vitamin C 23 Serum",
    searchQ: "COSRX Vitamin C 23 Serum",
    ingredientIds: ["vitaminc"],
    concerns: ["pigmentation", "dullness"],
    category: "serum",
    blurb: { fr: "Vitamine C pure à 23 % pour les taches tenaces.", en: "Pure 23% vitamin C for stubborn dark spots." },
  },
  {
    id: "cosrx-niacinamide15-serum",
    brand: "COSRX",
    name: "Niacinamide 15 Serum",
    searchQ: "COSRX Niacinamide 15",
    ingredientIds: ["niacinamide"],
    concerns: ["pores", "acne"],
    category: "serum",
    blurb: { fr: "Niacinamide concentrée : sébum et pores.", en: "Concentrated niacinamide: sebum and pores." },
  },
  {
    id: "cosrx-ha-essence",
    brand: "COSRX",
    name: "Hyaluronic Acid Hydra Power Essence",
    searchQ: "COSRX Hyaluronic Hydra Power Essence",
    ingredientIds: ["hyaluronic"],
    concerns: ["dehydration"],
    category: "essence",
    blurb: { fr: "Essence repulpante, hydratation longue durée.", en: "Plumping essence, long-lasting hydration." },
  },
  {
    id: "cosrx-balancium-cream",
    brand: "COSRX",
    name: "Balancium Comfort Ceramide Cream",
    searchQ: "COSRX Balancium Ceramide Cream",
    ingredientIds: ["ceramides", "centella"],
    concerns: ["barrier", "redness"],
    category: "moisturizer",
    blurb: { fr: "Centella et céramides pour apaiser et réparer.", en: "Centella and ceramides to soothe and repair." },
  },
  {
    id: "anua-heartleaf-cleansing-oil",
    brand: "Anua",
    name: "Heartleaf Pore Control Cleansing Oil",
    searchQ: "Anua Heartleaf Cleansing Oil",
    ingredientIds: ["heartleaf"],
    concerns: ["pores", "acne"],
    category: "cleanser",
    blurb: { fr: "Huile démaquillante au houttuynia, pores nets.", en: "Heartleaf cleansing oil for clear pores." },
  },
  {
    id: "anua-pdrn-ha-serum",
    brand: "Anua",
    name: "PDRN Hyaluronic Acid Capsule Serum",
    searchQ: "Anua PDRN Hyaluronic Serum",
    ingredientIds: ["hyaluronic"],
    concerns: ["dehydration", "aging"],
    category: "serum",
    blurb: { fr: "Hydratation intense et effet repulpant.", en: "Intense hydration with a plumping effect." },
  },
  {
    id: "anua-rice-glow-serum",
    brand: "Anua",
    name: "Rice 70 Glow Serum",
    searchQ: "Anua Rice 70 Serum",
    ingredientIds: ["rice", "niacinamide"],
    concerns: ["dullness", "pigmentation"],
    category: "serum",
    blurb: { fr: "Riz et niacinamide : éclat et teint unifié.", en: "Rice and niacinamide: glow and even tone." },
  },
  {
    id: "boj-dynasty-cream",
    brand: "Beauty of Joseon",
    name: "Dynasty Cream",
    searchQ: "Beauty of Joseon Dynasty Cream",
    ingredientIds: ["ginseng"],
    concerns: ["aging", "dehydration"],
    category: "moisturizer",
    blurb: { fr: "Ginseng et orchidée : nutrition et fermeté.", en: "Ginseng and orchid: nourishment and firmness." },
  },
  {
    id: "boj-greenplum-cleanser",
    brand: "Beauty of Joseon",
    name: "Green Plum Refreshing Cleanser",
    searchQ: "Beauty of Joseon Green Plum Cleanser",
    ingredientIds: ["salicylic"],
    concerns: ["acne", "pores"],
    category: "cleanser",
    blurb: { fr: "Nettoyant AHA/BHA doux au prune verte.", en: "Gentle AHA/BHA green-plum cleanser." },
  },
  {
    id: "skin1004-hyalucica-serum",
    brand: "SKIN1004",
    name: "Hyalu-Cica Water-Fit Serum",
    searchQ: "SKIN1004 Hyalu-Cica Serum",
    ingredientIds: ["hyaluronic", "centella"],
    concerns: ["dehydration", "barrier"],
    category: "serum",
    blurb: { fr: "Acide hyaluronique et centella : hydrate et apaise.", en: "Hyaluronic acid and centella: hydrates and soothes." },
  },
  {
    id: "skin1004-hyalucica-sun",
    brand: "SKIN1004",
    name: "Hyalu-Cica Water-Fit Sun Serum",
    searchQ: "SKIN1004 Hyalu-Cica Sun Serum",
    ingredientIds: ["hyaluronic", "centella"],
    concerns: ["dehydration", "barrier"],
    category: "sunscreen",
    blurb: { fr: "Protection hydratante au fini invisible.", en: "Hydrating protection with an invisible finish." },
  },
  {
    id: "skin1004-poreremedy-toner",
    brand: "SKIN1004",
    name: "Poremizing Pore Remedy Toner",
    searchQ: "SKIN1004 Pore Remedy Toner",
    ingredientIds: ["niacinamide", "salicylic"],
    concerns: ["pores", "acne"],
    category: "toner",
    blurb: { fr: "Niacinamide et BHA pour resserrer les pores.", en: "Niacinamide and BHA to refine pores." },
  },
  {
    id: "purito-galacto-niacin-essence",
    brand: "Purito",
    name: "Galacto Niacin 97 Power Essence",
    searchQ: "Purito Galacto Niacin 97",
    ingredientIds: ["galactomyces", "niacinamide"],
    concerns: ["dullness", "pigmentation"],
    category: "essence",
    blurb: { fr: "Ferment et niacinamide : éclat et grain de peau.", en: "Ferment and niacinamide: glow and texture." },
  },
  {
    id: "purito-dermide-cica-cream",
    brand: "Purito",
    name: "Dermide Cica Barrier Cream",
    searchQ: "Purito Dermide Cica Barrier",
    ingredientIds: ["ceramides", "centella"],
    concerns: ["barrier", "redness"],
    category: "moisturizer",
    blurb: { fr: "Céramides et centella pour barrière fragilisée.", en: "Ceramides and centella for a compromised barrier." },
  },
  {
    id: "purito-daily-go-to-sun",
    brand: "Purito",
    name: "Daily Go-To Sunscreen",
    searchQ: "Purito Daily Go-To Sunscreen",
    ingredientIds: ["centella"],
    concerns: ["barrier"],
    category: "sunscreen",
    blurb: { fr: "Protection quotidienne apaisante, sans fini blanc.", en: "Soothing daily protection, no white cast." },
  },
  {
    id: "klairs-supple-toner",
    brand: "Klairs",
    name: "Supple Preparation Unscented Toner",
    searchQ: "Klairs Supple Preparation Toner",
    ingredientIds: ["hyaluronic", "centella"],
    concerns: ["dehydration"],
    category: "toner",
    blurb: { fr: "Toner hydratant et apaisant, sans parfum.", en: "Hydrating, soothing toner, fragrance-free." },
  },
  {
    id: "imfrom-rice-toner",
    brand: "I'm From",
    name: "Rice Toner",
    searchQ: "I'm From Rice Toner",
    ingredientIds: ["rice"],
    concerns: ["dullness", "dehydration"],
    category: "toner",
    blurb: { fr: "77 % d'extrait de riz : éclat et confort.", en: "77% rice extract: glow and comfort." },
  },
  {
    id: "imfrom-mugwort-essence",
    brand: "I'm From",
    name: "Mugwort Essence",
    searchQ: "I'm From Mugwort Essence",
    ingredientIds: ["mugwort"],
    concerns: ["redness", "barrier"],
    category: "essence",
    blurb: { fr: "Armoise pure pour calmer les peaux réactives.", en: "Pure mugwort to calm reactive skin." },
  },
  {
    id: "isntree-watery-sun",
    brand: "Isntree",
    name: "Hyaluronic Acid Watery Sun Gel",
    searchQ: "Isntree Watery Sun Gel",
    ingredientIds: ["hyaluronic"],
    concerns: ["dehydration"],
    category: "sunscreen",
    blurb: { fr: "Protection légère et hydratante, toucher gel.", en: "Lightweight hydrating gel sunscreen." },
  },
  {
    id: "somebymi-snail-truecica-serum",
    brand: "Some By Mi",
    name: "Snail Truecica Miracle Repair Serum",
    searchQ: "Some By Mi Snail Truecica Serum",
    ingredientIds: ["snail", "centella"],
    concerns: ["barrier", "redness"],
    category: "serum",
    blurb: { fr: "Mucine et centella pour réparer et apaiser.", en: "Snail and centella to repair and soothe." },
  },
  {
    id: "somebymi-yuja-cleanser",
    brand: "Some By Mi",
    name: "Yuja Niacin Brightening Cleanser",
    searchQ: "Some By Mi Yuja Niacin Cleanser",
    ingredientIds: ["niacinamide"],
    concerns: ["dullness"],
    category: "cleanser",
    blurb: { fr: "Nettoyant éclat au yuja et niacinamide.", en: "Brightening yuja and niacinamide cleanser." },
  },
  {
    id: "illiyoon-ceramide-cream",
    brand: "Illiyoon",
    name: "Ceramide Ato Concentrate Cream",
    searchQ: "Illiyoon Ceramide Ato Cream",
    ingredientIds: ["ceramides"],
    concerns: ["barrier", "dehydration"],
    category: "moisturizer",
    blurb: { fr: "Céramides pour peaux sèches et fragilisées.", en: "Ceramides for dry, compromised skin." },
  },
  {
    id: "laneige-waterbank-cream",
    brand: "Laneige",
    name: "Water Bank Blue Hyaluronic Cream",
    searchQ: "Laneige Water Bank Cream",
    ingredientIds: ["hyaluronic"],
    concerns: ["dehydration"],
    category: "moisturizer",
    blurb: { fr: "Hydratation longue durée, texture fraîche.", en: "Long-lasting hydration, fresh texture." },
  },
  {
    id: "belif-aquabomb",
    brand: "belif",
    name: "The True Cream Aqua Bomb",
    searchQ: "belif Aqua Bomb",
    ingredientIds: ["hyaluronic"],
    concerns: ["dehydration"],
    category: "moisturizer",
    blurb: { fr: "Gel-crème désaltérant pour peaux normales à mixtes.", en: "Quenching gel-cream for normal-to-combination skin." },
  },
  {
    id: "medicube-pore-pad",
    brand: "Medicube",
    name: "Zero Pore Pad 2.0",
    searchQ: "Medicube Zero Pore Pad",
    ingredientIds: ["salicylic", "lactic"],
    concerns: ["pores"],
    category: "treatment",
    blurb: { fr: "Pads exfoliants pour pores et grain de peau.", en: "Exfoliating pads for pores and texture." },
  },
  {
    id: "medicube-collagen-serum",
    brand: "Medicube",
    name: "Collagen Niacinamide Serum",
    searchQ: "Medicube Collagen Niacinamide Serum",
    ingredientIds: ["peptides", "niacinamide"],
    concerns: ["aging", "dullness"],
    category: "serum",
    blurb: { fr: "Peptides et niacinamide pour fermeté et éclat.", en: "Peptides and niacinamide for firmness and glow." },
  },
  {
    id: "drceuracle-kombucha-essence",
    brand: "Dr.Ceuracle",
    name: "Vegan Kombucha Tea Essence",
    searchQ: "Dr.Ceuracle Kombucha Essence",
    ingredientIds: ["greentea"],
    concerns: ["dullness"],
    category: "essence",
    blurb: { fr: "Ferment de thé antioxydant pour l'éclat.", en: "Antioxidant tea ferment for radiance." },
  },
  {
    id: "manyo-galacniacin-essence",
    brand: "Ma:nyo",
    name: "Galac Niacin Essence",
    searchQ: "Manyo Galac Niacin Essence",
    ingredientIds: ["galactomyces", "niacinamide"],
    concerns: ["dullness", "pigmentation"],
    category: "essence",
    blurb: { fr: "Galactomyces et niacinamide : teint lumineux.", en: "Galactomyces and niacinamide: a luminous tone." },
  },
  {
    id: "heimish-matcha-toner",
    brand: "Heimish",
    name: "Matcha Biome Redness Relief Toner",
    searchQ: "Heimish Matcha Biome Toner",
    ingredientIds: ["greentea"],
    concerns: ["redness", "pores"],
    category: "toner",
    blurb: { fr: "Thé vert apaisant pour peaux sujettes aux rougeurs.", en: "Soothing green tea for redness-prone skin." },
  },
  {
    id: "tiam-vitc-source",
    brand: "TIA'M",
    name: "My Signature C Source",
    searchQ: "TIAM My Signature C Source",
    ingredientIds: ["vitaminc"],
    concerns: ["dullness", "pigmentation"],
    category: "serum",
    blurb: { fr: "Vitamine C abordable pour l'éclat au quotidien.", en: "Affordable vitamin C for daily glow." },
  },
  {
    id: "skinfood-rice-toner",
    brand: "SKINFOOD",
    name: "Rice Daily Brightening Toner",
    searchQ: "Skinfood Rice Toner",
    ingredientIds: ["rice"],
    concerns: ["dullness"],
    category: "toner",
    blurb: { fr: "Toner exfoliant doux au riz pour l'éclat.", en: "Gentle rice toner for brightness." },
  },
  {
    id: "roundlab-birch-cream",
    brand: "Round Lab",
    name: "Birch Juice Moisturizing Cream",
    searchQ: "Round Lab Birch Juice Cream",
    ingredientIds: ["hyaluronic"],
    concerns: ["dehydration", "barrier"],
    category: "moisturizer",
    blurb: { fr: "Sève de bouleau hydratante, fini confortable.", en: "Hydrating birch sap, comfortable finish." },
  },
  {
    id: "torriden-divein-cream",
    brand: "Torriden",
    name: "DIVE-IN Soothing Cream",
    searchQ: "Torriden DIVE-IN Cream",
    ingredientIds: ["hyaluronic"],
    concerns: ["dehydration"],
    category: "moisturizer",
    blurb: { fr: "Crème légère à l'acide hyaluronique multi-poids.", en: "Light multi-weight hyaluronic acid cream." },
  },
  {
    id: "drg-green-mild-sun",
    brand: "Dr.G",
    name: "Green Mild Up Sun",
    searchQ: "Dr.G Green Mild Up Sun",
    ingredientIds: ["centella"],
    concerns: ["barrier"],
    category: "sunscreen",
    blurb: { fr: "Protection douce à la centella, peaux sensibles.", en: "Gentle centella protection for sensitive skin." },
  },
  {
    id: "vt-reedle-shot",
    brand: "VT",
    name: "Reedle Shot 100",
    searchQ: "VT Reedle Shot 100",
    ingredientIds: ["centella", "niacinamide"],
    concerns: ["pores", "dullness"],
    category: "treatment",
    blurb: { fr: "Booster d'actifs pour grain de peau et éclat.", en: "Active booster for texture and radiance." },
  },
  {
    id: "goodal-heartleaf-serum",
    brand: "Goodal",
    name: "Houttuynia Cordata Calming Serum",
    searchQ: "Goodal Houttuynia Calming Serum",
    ingredientIds: ["heartleaf"],
    concerns: ["redness", "barrier"],
    category: "serum",
    blurb: { fr: "Houttuynia apaisant pour rougeurs et inconfort.", en: "Calming houttuynia for redness and discomfort." },
  },
  {
    id: "nacific-freshherb-toner",
    brand: "Nacific",
    name: "Fresh Herb Origin Toner",
    searchQ: "Nacific Fresh Herb Origin Toner",
    ingredientIds: ["centella"],
    concerns: ["redness", "pores"],
    category: "toner",
    blurb: { fr: "Toner aux herbes et centella, équilibre la peau.", en: "Herbal centella toner that balances skin." },
  },
  {
    id: "medicube-pdrn-serum",
    brand: "Medicube",
    name: "PDRN Pink Peptide Serum",
    searchQ: "Medicube PDRN Pink Peptide",
    ingredientIds: ["pdrn", "peptides"],
    concerns: ["aging", "barrier"],
    category: "serum",
    blurb: { fr: "PDRN et peptides : régénère et raffermit.", en: "PDRN and peptides: regenerates and firms." },
  },
  {
    id: "numbuzin-no5-serum",
    brand: "Numbuzin",
    name: "No.5 Vitamin-Niacinamide Concentrated Serum",
    searchQ: "numbuzin No.5 Vitamin Serum",
    ingredientIds: ["niacinamide", "vitaminc"],
    concerns: ["dullness", "pigmentation"],
    category: "serum",
    blurb: { fr: "Vitamines pour un teint plus clair et uni.", en: "Vitamins for a brighter, more even tone." },
  },
  {
    id: "skin1004-centella-cleansingoil",
    brand: "SKIN1004",
    name: "Madagascar Centella Light Cleansing Oil",
    searchQ: "SKIN1004 Centella Cleansing Oil",
    ingredientIds: ["centella"],
    concerns: ["redness", "pores"],
    category: "cleanser",
    blurb: { fr: "Huile démaquillante douce à la centella.", en: "Gentle centella cleansing oil." },
  },
  {
    id: "cosrx-centella-toner",
    brand: "COSRX",
    name: "Centella Water Alcohol-Free Toner",
    searchQ: "COSRX Centella Toner",
    ingredientIds: ["centella"],
    concerns: ["redness", "barrier"],
    category: "toner",
    blurb: { fr: "Toner apaisant sans alcool pour peaux sensibles.", en: "Soothing alcohol-free toner for sensitive skin." },
  },
  {
    id: "benton-aloe-bha-toner",
    brand: "Benton",
    name: "Aloe BHA Skin Toner",
    searchQ: "Benton Aloe BHA Toner",
    ingredientIds: ["aloe", "salicylic"],
    concerns: ["acne", "pores"],
    category: "toner",
    blurb: { fr: "Aloe et BHA : apaise et désincruste.", en: "Aloe and BHA: soothes and clears pores." },
  },
  {
    id: "benton-snailbee-essence",
    brand: "Benton",
    name: "Snail Bee High Content Essence",
    searchQ: "Benton Snail Bee Essence",
    ingredientIds: ["snail"],
    concerns: ["barrier", "dehydration"],
    category: "essence",
    blurb: { fr: "Mucine et propolis : répare et hydrate.", en: "Snail and propolis: repairs and hydrates." },
  },
  {
    id: "klairs-rich-moist-cream",
    brand: "Klairs",
    name: "Rich Moist Soothing Cream",
    searchQ: "Klairs Rich Moist Cream",
    ingredientIds: ["ceramides"],
    concerns: ["barrier", "dehydration"],
    category: "moisturizer",
    blurb: { fr: "Crème réparatrice aux céramides, fini confortable.", en: "Ceramide repair cream with a comfortable finish." },
  },
  {
    id: "drjart-cicapair-cream",
    brand: "Dr.Jart+",
    name: "Cicapair Tiger Grass Cream",
    searchQ: "Dr.Jart Cicapair Cream",
    ingredientIds: ["centella", "madecassoside"],
    concerns: ["redness", "barrier"],
    category: "moisturizer",
    blurb: { fr: "Centella concentrée pour peaux réactives.", en: "Concentrated centella for reactive skin." },
  },
  {
    id: "purito-oatin-cream",
    brand: "Purito",
    name: "Oat-in Calming Gel Cream",
    searchQ: "Purito Oat-in Cream",
    ingredientIds: ["oat"],
    concerns: ["redness", "barrier"],
    category: "moisturizer",
    blurb: { fr: "Avoine apaisante pour démangeaisons et rougeurs.", en: "Calming oat for itch and redness." },
  },
  {
    id: "roundlab-pine-cica",
    brand: "Round Lab",
    name: "Pine Calming Cica Cream",
    searchQ: "Round Lab Pine Cica Cream",
    ingredientIds: ["centella"],
    concerns: ["redness", "barrier"],
    category: "moisturizer",
    blurb: { fr: "Pin et centella pour calmer et réparer.", en: "Pine and centella to calm and repair." },
  },
  {
    id: "torriden-cellmazing-serum",
    brand: "Torriden",
    name: "Cellmazing Hyaluronic Acid Serum",
    searchQ: "Torriden Cellmazing Serum",
    ingredientIds: ["hyaluronic"],
    concerns: ["dehydration"],
    category: "serum",
    blurb: { fr: "Hydratation rebondie à l'acide hyaluronique.", en: "Bouncy hyaluronic acid hydration." },
  },
  {
    id: "marynmay-teatree-cica",
    brand: "Mary&May",
    name: "Tea Tree Cica Serum",
    searchQ: "Mary May Tea Tree Cica",
    ingredientIds: ["teatree", "centella"],
    concerns: ["acne", "redness"],
    category: "serum",
    blurb: { fr: "Arbre à thé et centella pour les imperfections.", en: "Tea tree and centella for blemishes." },
  },
  {
    id: "iunik-teatree-serum",
    brand: "iUNIK",
    name: "Tea Tree Relief Serum",
    searchQ: "iUNIK Tea Tree Serum",
    ingredientIds: ["teatree", "centella"],
    concerns: ["acne", "redness"],
    category: "serum",
    blurb: { fr: "Sérum purifiant pour peaux à imperfections.", en: "Purifying serum for blemish-prone skin." },
  },
  {
    id: "iunik-betaglucan-serum",
    brand: "iUNIK",
    name: "Beta Glucan Power Moisture Serum",
    searchQ: "iUNIK Beta Glucan Serum",
    ingredientIds: ["betaglucan"],
    concerns: ["dehydration", "barrier"],
    category: "serum",
    blurb: { fr: "Bêta-glucane pour une hydratation profonde et apaisante.", en: "Beta-glucan for deep, soothing hydration." },
  },
  {
    id: "iunik-propolis-serum",
    brand: "iUNIK",
    name: "Propolis Vitamin Synergy Serum",
    searchQ: "iUNIK Propolis Serum",
    ingredientIds: ["propolis", "vitaminc"],
    concerns: ["dullness", "barrier"],
    category: "serum",
    blurb: { fr: "Propolis et vitamines pour éclat et confort.", en: "Propolis and vitamins for glow and comfort." },
  },
  {
    id: "pyunkangyul-calming-serum",
    brand: "Pyunkang Yul",
    name: "Calming Moisture Serum",
    searchQ: "Pyunkang Yul Calming Serum",
    ingredientIds: ["centella"],
    concerns: ["redness", "barrier"],
    category: "serum",
    blurb: { fr: "Sérum minimaliste apaisant pour peaux sensibles.", en: "Minimalist calming serum for sensitive skin." },
  },
  {
    id: "manyo-bifida-ampoule",
    brand: "Ma:nyo",
    name: "Bifida Biome Complex Ampoule",
    searchQ: "Manyo Bifida Ampoule",
    ingredientIds: ["bifida"],
    concerns: ["barrier", "redness"],
    category: "serum",
    blurb: { fr: "Ferment de bifida pour renforcer la barrière.", en: "Bifida ferment to strengthen the barrier." },
  },
  {
    id: "boj-greentea-serum",
    brand: "Beauty of Joseon",
    name: "Calming Serum: Green Tea + Panthenol",
    searchQ: "Beauty of Joseon Calming Serum",
    ingredientIds: ["greentea", "panthenol"],
    concerns: ["redness", "acne"],
    category: "serum",
    blurb: { fr: "Thé vert et panthénol pour apaiser et hydrater.", en: "Green tea and panthenol to soothe and hydrate." },
  },
  {
    id: "abib-collagen-mask",
    brand: "Abib",
    name: "Collagen Eye Patch / Gel Mask",
    searchQ: "Abib Collagen Mask",
    ingredientIds: ["collagen"],
    concerns: ["dehydration", "aging"],
    category: "mask",
    blurb: { fr: "Collagène repulpant pour un coup d'éclat.", en: "Plumping collagen for an instant glow." },
  },
  {
    id: "dalba-truffle-serum",
    brand: "d'Alba",
    name: "White Truffle Vitalizing Serum",
    searchQ: "dAlba White Truffle Serum",
    ingredientIds: ["niacinamide"],
    concerns: ["dullness", "dehydration"],
    category: "serum",
    blurb: { fr: "Sérum vitalisant à la truffe blanche, fini lumineux.", en: "White-truffle vitalizing serum with a luminous finish." },
  },
  {
    id: "innisfree-greentea-serum",
    brand: "innisfree",
    name: "Green Tea Seed Hyaluronic Serum",
    searchQ: "innisfree Green Tea Seed Serum",
    ingredientIds: ["greentea", "hyaluronic"],
    concerns: ["dehydration", "dullness"],
    category: "serum",
    blurb: { fr: "Thé vert et hydratation pour un teint frais.", en: "Green tea and hydration for a fresh complexion." },
  },
  {
    id: "innisfree-retinol-cica",
    brand: "innisfree",
    name: "Retinol Cica Repair Ampoule",
    searchQ: "innisfree Retinol Cica Ampoule",
    ingredientIds: ["retinol", "centella"],
    concerns: ["aging"],
    category: "treatment",
    blurb: { fr: "Rétinol encadré de centella, plus tolérable.", en: "Retinol buffered with centella, more tolerable." },
  },
  {
    id: "laneige-sleeping-mask",
    brand: "Laneige",
    name: "Water Sleeping Mask",
    searchQ: "Laneige Water Sleeping Mask",
    ingredientIds: ["hyaluronic"],
    concerns: ["dehydration"],
    category: "mask",
    blurb: { fr: "Masque de nuit repulpant pour peaux assoiffées.", en: "Plumping overnight mask for thirsty skin." },
  },
  {
    id: "cosrx-aloe-sun",
    brand: "COSRX",
    name: "Aloe Soothing Sun Cream SPF50+",
    searchQ: "COSRX Aloe Sun Cream",
    ingredientIds: ["aloe"],
    concerns: ["barrier"],
    category: "sunscreen",
    blurb: { fr: "Protection apaisante à l'aloe, sans inconfort.", en: "Soothing aloe protection, no discomfort." },
  },
  {
    id: "purito-centella-buffet",
    brand: "Purito",
    name: "Centella Green Level Buffet Serum",
    searchQ: "Purito Centella Buffet Serum",
    ingredientIds: ["centella", "niacinamide"],
    concerns: ["redness", "barrier"],
    category: "serum",
    blurb: { fr: "Centella et peptides pour apaiser et renforcer.", en: "Centella and peptides to soothe and strengthen." },
  },
  {
    id: "tocobo-bifida-essence",
    brand: "Tocobo",
    name: "Bifida Biome Essence",
    searchQ: "Tocobo Bifida Essence",
    ingredientIds: ["bifida"],
    concerns: ["barrier", "redness"],
    category: "essence",
    blurb: { fr: "Essence ferment pour un microbiome équilibré.", en: "Ferment essence for a balanced microbiome." },
  },
  {
    id: "abib-mugwort-pad",
    brand: "Abib",
    name: "Heartleaf Calming Pad / Mugwort",
    searchQ: "Abib Mugwort Calming Pad",
    ingredientIds: ["mugwort"],
    concerns: ["redness", "pores"],
    category: "treatment",
    blurb: { fr: "Pads apaisants à l'armoise pour peaux réactives.", en: "Soothing mugwort pads for reactive skin." },
  },
  {
    id: "haruharu-blackrice-serum",
    brand: "Haruharu Wonder",
    name: "Black Rice Hyaluronic Serum",
    searchQ: "Haruharu Wonder Black Rice Serum",
    ingredientIds: ["rice", "hyaluronic"],
    concerns: ["dullness", "dehydration"],
    category: "serum",
    blurb: { fr: "Riz noir fermenté et hydratation pour l'éclat.", en: "Fermented black rice and hydration for glow." },
  },
  {
    id: "medicube-collagen-cream",
    brand: "Medicube",
    name: "Collagen Niacinamide Cream",
    searchQ: "Medicube Collagen Cream",
    ingredientIds: ["collagen", "niacinamide"],
    concerns: ["aging", "dehydration"],
    category: "moisturizer",
    blurb: { fr: "Collagène et niacinamide pour fermeté et éclat.", en: "Collagen and niacinamide for firmness and glow." },
  },
  {
    id: "goodal-greentangerine-cream",
    brand: "Goodal",
    name: "Green Tangerine Vita C Cream",
    searchQ: "Goodal Green Tangerine Cream",
    ingredientIds: ["vitaminc"],
    concerns: ["pigmentation", "dullness"],
    category: "moisturizer",
    blurb: { fr: "Crème vitamine C ciblant les taches.", en: "Vitamin C cream targeting dark spots." },
  },
];

/** Products whose ingredientIds intersect `ids`, de-duplicated,
 *  preserving the input id priority order, capped at `max`. */
export function productsForIngredients(ids: string[], max = 6): Product[] {
  const out: Product[] = [];
  const seen = new Set<string>();
  for (const id of ids) {
    for (const p of PRODUCTS) {
      if (seen.has(p.id)) continue;
      if (p.ingredientIds.includes(id)) {
        out.push(p);
        seen.add(p.id);
        if (out.length >= max) return out;
      }
    }
  }
  return out;
}
